<template><h1 id="代码片段" tabindex="-1"><a class="header-anchor" href="#代码片段" aria-hidden="true">#</a> 代码片段</h1>
<h2 id="object-defineproperty" tabindex="-1"><a class="header-anchor" href="#object-defineproperty" aria-hidden="true">#</a> Object.defineProperty()</h2>
<p>Object.defineProperty()方法会直接在一个对象上定义一个新属性,或者修改一个对象的现有属性,并返回此对象。</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="shiki" style="background-color: #272822"><code><span class="line"><span style="color: #66D9EF; font-style: italic">function</span><span style="color: #F8F8F2"> </span><span style="color: #A6E22E">Archiver</span><span style="color: #F8F8F2">() {</span></span>
<span class="line"><span style="color: #F8F8F2">  </span><span style="color: #66D9EF; font-style: italic">let</span><span style="color: #F8F8F2"> temperature </span><span style="color: #F92672">=</span><span style="color: #F8F8F2"> </span><span style="color: #AE81FF">null</span><span style="color: #F8F8F2">;</span></span>
<span class="line"><span style="color: #F8F8F2">  </span><span style="color: #66D9EF; font-style: italic">var</span><span style="color: #F8F8F2"> archive </span><span style="color: #F92672">=</span><span style="color: #F8F8F2"> []</span></span>
<span class="line"><span style="color: #F8F8F2">  </span><span style="color: #66D9EF; font-style: italic">Object</span><span style="color: #F8F8F2">.</span><span style="color: #A6E22E">defineProperty</span><span style="color: #F8F8F2">(</span><span style="color: #FD971F">this</span><span style="color: #F8F8F2">, </span><span style="color: #E6DB74">&#39;temperature&#39;</span><span style="color: #F8F8F2">, {</span></span>
<span class="line"><span style="color: #F8F8F2">    </span><span style="color: #A6E22E">get</span><span style="color: #F8F8F2">:</span><span style="color: #66D9EF; font-style: italic">function</span><span style="color: #F8F8F2">() {</span></span>
<span class="line"><span style="color: #F8F8F2">      </span><span style="color: #F92672">return</span><span style="color: #F8F8F2"> temperature</span></span>
<span class="line"><span style="color: #F8F8F2">    },</span></span>
<span class="line"><span style="color: #F8F8F2">    </span><span style="color: #A6E22E">set</span><span style="color: #F8F8F2">:</span><span style="color: #66D9EF; font-style: italic">function</span><span style="color: #F8F8F2">(</span><span style="color: #FD971F; font-style: italic">value</span><span style="color: #F8F8F2">) {</span></span>
<span class="line"><span style="color: #F8F8F2">      temperature </span><span style="color: #F92672">=</span><span style="color: #F8F8F2"> value;</span></span>
<span class="line"><span style="color: #F8F8F2">      archive.</span><span style="color: #A6E22E">push</span><span style="color: #F8F8F2">({value:temperature})</span></span>
<span class="line"><span style="color: #F8F8F2">    }</span></span>
<span class="line"><span style="color: #F8F8F2">  })</span></span>
<span class="line"><span style="color: #F8F8F2">  </span><span style="color: #FD971F">this</span><span style="color: #F8F8F2">.</span><span style="color: #A6E22E">getArchive</span><span style="color: #F8F8F2"> </span><span style="color: #F92672">=</span><span style="color: #F8F8F2"> </span><span style="color: #66D9EF; font-style: italic">function</span><span style="color: #F8F8F2">() {</span></span>
<span class="line"><span style="color: #F8F8F2">    </span><span style="color: #F92672">return</span><span style="color: #F8F8F2"> archive</span></span>
<span class="line"><span style="color: #F8F8F2">  }</span></span>
<span class="line"><span style="color: #F8F8F2">}</span></span>
<span class="line"><span style="color: #66D9EF; font-style: italic">const</span><span style="color: #F8F8F2"> arc </span><span style="color: #F92672">=</span><span style="color: #F8F8F2"> </span><span style="color: #F92672">new</span><span style="color: #F8F8F2"> </span><span style="color: #A6E22E">Archiver</span><span style="color: #F8F8F2">()</span></span>
<span class="line"><span style="color: #F8F8F2">arc.temperature </span><span style="color: #F92672">=</span><span style="color: #F8F8F2"> </span><span style="color: #AE81FF">11</span></span>
<span class="line"><span style="color: #F8F8F2">console.</span><span style="color: #A6E22E">log</span><span style="color: #F8F8F2">(arc.temperature)  </span><span style="color: #88846F">// 11</span></span>
<span class="line"><span style="color: #F8F8F2">arc.temperature </span><span style="color: #F92672">=</span><span style="color: #F8F8F2"> </span><span style="color: #AE81FF">12</span><span style="color: #F8F8F2">;</span></span>
<span class="line"><span style="color: #F8F8F2">arc.temperature </span><span style="color: #F92672">=</span><span style="color: #F8F8F2"> </span><span style="color: #AE81FF">13</span><span style="color: #F8F8F2">;</span></span>
<span class="line"><span style="color: #F8F8F2">console.</span><span style="color: #A6E22E">log</span><span style="color: #F8F8F2">(arc.</span><span style="color: #A6E22E">getArchive</span><span style="color: #F8F8F2">());</span></span>
<span class="line"><span style="color: #88846F">/*</span></span>
<span class="line"><span style="color: #88846F">[{value: 11},{value: 12},{value: 13}]</span></span>
<span class="line"><span style="color: #88846F">*/</span></span>
<span class="line"></span></code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="isnative-ctor" tabindex="-1"><a class="header-anchor" href="#isnative-ctor" aria-hidden="true">#</a> isNative(Ctor)</h2>
<p>判断浏览器对某些原生方法对支持情况。如Proxy, Promise, Map, Symbol等。</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="shiki" style="background-color: #272822"><code><span class="line"><span style="color: #66D9EF; font-style: italic">function</span><span style="color: #F8F8F2"> </span><span style="color: #A6E22E">isNative</span><span style="color: #F8F8F2">(</span><span style="color: #FD971F; font-style: italic">Ctor</span><span style="color: #F8F8F2">){</span></span>
<span class="line"><span style="color: #F8F8F2">  </span><span style="color: #F92672">return</span><span style="color: #F8F8F2"> </span><span style="color: #F92672">typeof</span><span style="color: #F8F8F2"> Ctor </span><span style="color: #F92672">===</span><span style="color: #F8F8F2"> </span><span style="color: #E6DB74">&#39;function&#39;</span><span style="color: #F8F8F2"> </span><span style="color: #F92672">&amp;&amp;</span><span style="color: #E6DB74"> /native code/</span><span style="color: #F8F8F2">.</span><span style="color: #A6E22E">test</span><span style="color: #F8F8F2">(Ctor.</span><span style="color: #A6E22E">toString</span><span style="color: #F8F8F2">())</span></span>
<span class="line"><span style="color: #F8F8F2">}</span></span>
<span class="line"></span>
<span class="line"><span style="color: #88846F">//--------------------------</span></span>
<span class="line"><span style="color: #A6E22E">isNative</span><span style="color: #F8F8F2">(</span><span style="color: #66D9EF; font-style: italic">Object</span><span style="color: #F8F8F2">)   </span><span style="color: #88846F">// true</span></span>
<span class="line"><span style="color: #A6E22E">isNative</span><span style="color: #F8F8F2">(</span><span style="color: #66D9EF; font-style: italic">String</span><span style="color: #F8F8F2">)   </span><span style="color: #88846F">// true</span></span>
<span class="line"><span style="color: #A6E22E">isNative</span><span style="color: #F8F8F2">(</span><span style="color: #66D9EF; font-style: italic">Number</span><span style="color: #F8F8F2">)   </span><span style="color: #88846F">// true</span></span>
<span class="line"><span style="color: #A6E22E">isNative</span><span style="color: #F8F8F2">(</span><span style="color: #66D9EF; font-style: italic">Proxy</span><span style="color: #F8F8F2">)    </span><span style="color: #88846F">// true</span></span>
<span class="line"><span style="color: #A6E22E">isNative</span><span style="color: #F8F8F2">(</span><span style="color: #66D9EF; font-style: italic">Promise</span><span style="color: #F8F8F2">)  </span><span style="color: #88846F">// true</span></span>
<span class="line"><span style="color: #A6E22E">isNative</span><span style="color: #F8F8F2">(</span><span style="color: #66D9EF; font-style: italic">Date</span><span style="color: #F8F8F2">)     </span><span style="color: #88846F">// true</span></span>
<span class="line"><span style="color: #A6E22E">isNative</span><span style="color: #F8F8F2">(</span><span style="color: #66D9EF; font-style: italic">Function</span><span style="color: #F8F8F2">) </span><span style="color: #88846F">// true</span></span>
<span class="line"><span style="color: #A6E22E">isNative</span><span style="color: #F8F8F2">(</span><span style="color: #66D9EF; font-style: italic">Boolean</span><span style="color: #F8F8F2">)  </span><span style="color: #88846F">// true</span></span>
<span class="line"><span style="color: #A6E22E">isNative</span><span style="color: #F8F8F2">(</span><span style="color: #66D9EF; font-style: italic">Symbol</span><span style="color: #F8F8F2">)   </span><span style="color: #88846F">// true</span></span>
<span class="line"><span style="color: #66D9EF; font-style: italic">Object</span><span style="color: #F8F8F2">.</span><span style="color: #A6E22E">toString</span><span style="color: #F8F8F2">(), </span><span style="color: #F92672">typeof</span><span style="color: #F8F8F2"> </span><span style="color: #66D9EF; font-style: italic">Object</span><span style="color: #F8F8F2">.</span><span style="color: #A6E22E">toString</span><span style="color: #F8F8F2">()  </span></span>
<span class="line"><span style="color: #88846F">// function Object() { [native code] } string</span></span>
<span class="line"></span>
<span class="line"><span style="color: #66D9EF; font-style: italic">Symbol</span><span style="color: #F8F8F2">.</span><span style="color: #A6E22E">toString</span><span style="color: #F8F8F2">(), </span><span style="color: #F92672">typeof</span><span style="color: #F8F8F2"> </span><span style="color: #66D9EF; font-style: italic">Symbol</span><span style="color: #F8F8F2">.</span><span style="color: #A6E22E">toString</span><span style="color: #F8F8F2">()  </span></span>
<span class="line"><span style="color: #88846F">// function Symbol() { [native code] } string</span></span>
<span class="line"></span></code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="千分位转化数字" tabindex="-1"><a class="header-anchor" href="#千分位转化数字" aria-hidden="true">#</a> 千分位转化数字</h2>
<div class="language-typescript ext-ts line-numbers-mode"><pre v-pre class="shiki" style="background-color: #272822"><code><span class="line"><span style="color: #88846F">// 暂只考虑正整数</span></span>
<span class="line"><span style="color: #88846F">// ---- 使用数组的reduce方法 ----</span></span>
<span class="line"><span style="color: #66D9EF; font-style: italic">function</span><span style="color: #F8F8F2"> </span><span style="color: #A6E22E">format1</span><span style="color: #F8F8F2">(</span><span style="color: #FD971F; font-style: italic">money</span><span style="color: #F92672">:</span><span style="color: #F8F8F2"> </span><span style="color: #66D9EF; font-style: italic">number</span><span style="color: #F8F8F2">)</span><span style="color: #F92672">:</span><span style="color: #F8F8F2"> </span><span style="color: #66D9EF; font-style: italic">number</span><span style="color: #F8F8F2"> </span><span style="color: #F92672">|</span><span style="color: #F8F8F2"> </span><span style="color: #66D9EF; font-style: italic">string</span><span style="color: #F8F8F2"> {</span></span>
<span class="line"><span style="color: #F8F8F2">  </span><span style="color: #F92672">if</span><span style="color: #F8F8F2">(money </span><span style="color: #F92672">&gt;=</span><span style="color: #F8F8F2"> </span><span style="color: #AE81FF">0</span><span style="color: #F8F8F2"> </span><span style="color: #F92672">&amp;&amp;</span><span style="color: #F8F8F2"> money </span><span style="color: #F92672">&lt;=</span><span style="color: #F8F8F2"> </span><span style="color: #AE81FF">999</span><span style="color: #F8F8F2">) </span><span style="color: #F92672">return</span><span style="color: #F8F8F2"> money</span></span>
<span class="line"><span style="color: #F8F8F2">  </span><span style="color: #66D9EF; font-style: italic">const</span><span style="color: #F8F8F2"> array </span><span style="color: #F92672">=</span><span style="color: #F8F8F2"> money.</span><span style="color: #A6E22E">toString</span><span style="color: #F8F8F2">().</span><span style="color: #A6E22E">split</span><span style="color: #F8F8F2">(</span><span style="color: #E6DB74">&#39;&#39;</span><span style="color: #F8F8F2">).</span><span style="color: #A6E22E">reverse</span><span style="color: #F8F8F2">()</span></span>
<span class="line"><span style="color: #F8F8F2">  </span><span style="color: #88846F">// [7,6,5,4,3,2,1]</span></span>
<span class="line"><span style="color: #F8F8F2">  </span><span style="color: #F92672">return</span><span style="color: #F8F8F2"> array.</span><span style="color: #A6E22E">reduce</span><span style="color: #F8F8F2">((</span><span style="color: #FD971F; font-style: italic">prev</span><span style="color: #F8F8F2">,</span><span style="color: #FD971F; font-style: italic">next</span><span style="color: #F8F8F2">,</span><span style="color: #FD971F; font-style: italic">i</span><span style="color: #F8F8F2">) </span><span style="color: #66D9EF; font-style: italic">=&gt;</span><span style="color: #F8F8F2"> {</span></span>
<span class="line"><span style="color: #F8F8F2">    </span><span style="color: #F92672">if</span><span style="color: #F8F8F2">(i </span><span style="color: #F92672">%</span><span style="color: #F8F8F2"> </span><span style="color: #AE81FF">3</span><span style="color: #F8F8F2"> </span><span style="color: #F92672">===</span><span style="color: #F8F8F2"> </span><span style="color: #AE81FF">0</span><span style="color: #F8F8F2"> </span><span style="color: #F92672">&amp;&amp;</span><span style="color: #F8F8F2"> i </span><span style="color: #F92672">!==</span><span style="color: #F8F8F2"> </span><span style="color: #AE81FF">0</span><span style="color: #F8F8F2">) {</span></span>
<span class="line"><span style="color: #F8F8F2">      </span><span style="color: #F92672">return</span><span style="color: #F8F8F2"> next </span><span style="color: #F92672">+</span><span style="color: #F8F8F2"> </span><span style="color: #E6DB74">&#39;,&#39;</span><span style="color: #F8F8F2"> </span><span style="color: #F92672">+</span><span style="color: #F8F8F2"> prev</span></span>
<span class="line"><span style="color: #F8F8F2">    }</span><span style="color: #F92672">else</span><span style="color: #F8F8F2">{</span></span>
<span class="line"><span style="color: #F8F8F2">      </span><span style="color: #F92672">return</span><span style="color: #F8F8F2"> next </span><span style="color: #F92672">+</span><span style="color: #F8F8F2"> prev</span></span>
<span class="line"><span style="color: #F8F8F2">    }</span></span>
<span class="line"><span style="color: #F8F8F2">  }, </span><span style="color: #E6DB74">&#39;&#39;</span><span style="color: #F8F8F2">)</span></span>
<span class="line"><span style="color: #F8F8F2">}</span></span>
<span class="line"><span style="color: #66D9EF; font-style: italic">const</span><span style="color: #F8F8F2"> number </span><span style="color: #F92672">=</span><span style="color: #F8F8F2"> </span><span style="color: #AE81FF">1234567</span><span style="color: #F8F8F2">;</span></span>
<span class="line"><span style="color: #F8F8F2">console.</span><span style="color: #A6E22E">log</span><span style="color: #F8F8F2">(</span><span style="color: #A6E22E">format</span><span style="color: #F8F8F2">(number)) </span><span style="color: #88846F">// 1,234,567</span></span>
<span class="line"></span>
<span class="line"></span>
<span class="line"><span style="color: #88846F">// --- 使用字符串的方法 -----</span></span>
<span class="line"><span style="color: #66D9EF; font-style: italic">function</span><span style="color: #F8F8F2"> </span><span style="color: #A6E22E">format2</span><span style="color: #F8F8F2">(</span><span style="color: #FD971F; font-style: italic">money</span><span style="color: #F92672">:</span><span style="color: #F8F8F2"> </span><span style="color: #66D9EF; font-style: italic">number</span><span style="color: #F8F8F2">)</span><span style="color: #F92672">:</span><span style="color: #F8F8F2"> </span><span style="color: #66D9EF; font-style: italic">number</span><span style="color: #F8F8F2"> </span><span style="color: #F92672">|</span><span style="color: #F8F8F2"> </span><span style="color: #66D9EF; font-style: italic">string</span><span style="color: #F8F8F2"> {</span></span>
<span class="line"><span style="color: #F8F8F2">  </span><span style="color: #F92672">if</span><span style="color: #F8F8F2">(money </span><span style="color: #F92672">&gt;=</span><span style="color: #F8F8F2"> </span><span style="color: #AE81FF">0</span><span style="color: #F8F8F2"> </span><span style="color: #F92672">&amp;&amp;</span><span style="color: #F8F8F2"> money </span><span style="color: #F92672">&lt;=</span><span style="color: #F8F8F2"> </span><span style="color: #AE81FF">999</span><span style="color: #F8F8F2">) </span><span style="color: #F92672">return</span><span style="color: #F8F8F2"> money</span></span>
<span class="line"><span style="color: #F8F8F2">  </span><span style="color: #66D9EF; font-style: italic">const</span><span style="color: #F8F8F2"> string </span><span style="color: #F92672">=</span><span style="color: #F8F8F2"> money.</span><span style="color: #A6E22E">toString</span><span style="color: #F8F8F2">()</span></span>
<span class="line"><span style="color: #F8F8F2">  </span><span style="color: #66D9EF; font-style: italic">const</span><span style="color: #F8F8F2"> length </span><span style="color: #F92672">=</span><span style="color: #F8F8F2"> string.length</span></span>
<span class="line"><span style="color: #F8F8F2">  </span><span style="color: #88846F">// 1234567</span></span>
<span class="line"><span style="color: #F8F8F2">  </span><span style="color: #66D9EF; font-style: italic">let</span><span style="color: #F8F8F2"> str </span><span style="color: #F92672">=</span><span style="color: #F8F8F2"> </span><span style="color: #E6DB74">&#39;&#39;</span><span style="color: #F8F8F2">;</span></span>
<span class="line"><span style="color: #F8F8F2">  </span><span style="color: #88846F">//i 6 / j 1</span></span>
<span class="line"><span style="color: #F8F8F2">  </span><span style="color: #F92672">for</span><span style="color: #F8F8F2">(</span><span style="color: #66D9EF; font-style: italic">let</span><span style="color: #F8F8F2"> i </span><span style="color: #F92672">=</span><span style="color: #F8F8F2"> length </span><span style="color: #F92672">-</span><span style="color: #F8F8F2"> </span><span style="color: #AE81FF">1</span><span style="color: #F8F8F2">; i </span><span style="color: #F92672">&gt;=</span><span style="color: #F8F8F2"> </span><span style="color: #AE81FF">0</span><span style="color: #F8F8F2">; i</span><span style="color: #F92672">--</span><span style="color: #F8F8F2">) {</span></span>
<span class="line"><span style="color: #F8F8F2">    </span><span style="color: #66D9EF; font-style: italic">const</span><span style="color: #F8F8F2"> j </span><span style="color: #F92672">=</span><span style="color: #F8F8F2"> length </span><span style="color: #F92672">-</span><span style="color: #F8F8F2"> i </span><span style="color: #F92672">-</span><span style="color: #F8F8F2"> </span><span style="color: #AE81FF">1</span></span>
<span class="line"><span style="color: #F8F8F2">    </span><span style="color: #F92672">if</span><span style="color: #F8F8F2">(j </span><span style="color: #F92672">%</span><span style="color: #F8F8F2"> </span><span style="color: #AE81FF">3</span><span style="color: #F8F8F2"> </span><span style="color: #F92672">===</span><span style="color: #F8F8F2"> </span><span style="color: #AE81FF">0</span><span style="color: #F8F8F2"> </span><span style="color: #F92672">&amp;&amp;</span><span style="color: #F8F8F2"> j </span><span style="color: #F92672">!==</span><span style="color: #F8F8F2"> </span><span style="color: #AE81FF">0</span><span style="color: #F8F8F2">) {</span></span>
<span class="line"><span style="color: #F8F8F2">      str </span><span style="color: #F92672">=</span><span style="color: #F8F8F2"> string[i] </span><span style="color: #F92672">+</span><span style="color: #F8F8F2"> </span><span style="color: #E6DB74">&#39;,&#39;</span><span style="color: #F8F8F2"> </span><span style="color: #F92672">+</span><span style="color: #F8F8F2"> str</span></span>
<span class="line"><span style="color: #F8F8F2">    }</span><span style="color: #F92672">else</span><span style="color: #F8F8F2">{</span></span>
<span class="line"><span style="color: #F8F8F2">      str </span><span style="color: #F92672">=</span><span style="color: #F8F8F2"> string[i] </span><span style="color: #F92672">+</span><span style="color: #F8F8F2"> str</span></span>
<span class="line"><span style="color: #F8F8F2">    }</span></span>
<span class="line"><span style="color: #F8F8F2">  }</span></span>
<span class="line"><span style="color: #F8F8F2">  </span><span style="color: #F92672">return</span><span style="color: #F8F8F2"> str</span></span>
<span class="line"><span style="color: #F8F8F2">}</span></span>
<span class="line"><span style="color: #66D9EF; font-style: italic">const</span><span style="color: #F8F8F2"> number </span><span style="color: #F92672">=</span><span style="color: #F8F8F2"> </span><span style="color: #AE81FF">1234567678</span></span>
<span class="line"><span style="color: #F8F8F2">console.</span><span style="color: #A6E22E">log</span><span style="color: #F8F8F2">(</span><span style="color: #A6E22E">format2</span><span style="color: #F8F8F2">(number)) </span><span style="color: #88846F">// 1,234,567,678</span></span>
<span class="line"></span></code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></template>
