<template><div><h1 id="高阶函数" tabindex="-1"><a class="header-anchor" href="#高阶函数" aria-hidden="true">#</a> 高阶函数</h1>
<h2 id="pure-function" tabindex="-1"><a class="header-anchor" href="#pure-function" aria-hidden="true">#</a> Pure Function</h2>
<p>函数输出的结果取决于传入的参数,不会产生副作用,相同的输入会有相同的输出。</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="shiki" style="background-color: #272822"><code><span class="line"><span style="color: #66D9EF; font-style: italic">function</span><span style="color: #F8F8F2"> </span><span style="color: #A6E22E">sum</span><span style="color: #F8F8F2">(</span><span style="color: #FD971F; font-style: italic">x</span><span style="color: #F8F8F2">,</span><span style="color: #FD971F; font-style: italic">y</span><span style="color: #F8F8F2">){</span></span>
<span class="line"><span style="color: #F8F8F2">  </span><span style="color: #F92672">return</span><span style="color: #F8F8F2"> x </span><span style="color: #F92672">+</span><span style="color: #F8F8F2"> y;</span></span>
<span class="line"><span style="color: #F8F8F2">}</span></span>
<span class="line"><span style="color: #88846F">// 上面的函数就是一个纯函数,每次输入相同的值都会返回相同的结果</span></span>
<span class="line"><span style="color: #A6E22E">sum</span><span style="color: #F8F8F2">(</span><span style="color: #AE81FF">3</span><span style="color: #F8F8F2">,</span><span style="color: #AE81FF">4</span><span style="color: #F8F8F2">)  </span><span style="color: #88846F">// 7</span></span>
<span class="line"><span style="color: #A6E22E">sum</span><span style="color: #F8F8F2">(</span><span style="color: #AE81FF">3</span><span style="color: #F8F8F2">,</span><span style="color: #AE81FF">4</span><span style="color: #F8F8F2">)  </span><span style="color: #88846F">// 7</span></span>
<span class="line"></span></code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>副作用指使外部环境发生了可观察的变化</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="shiki" style="background-color: #272822"><code><span class="line"><span style="color: #66D9EF; font-style: italic">const</span><span style="color: #F8F8F2"> bag </span><span style="color: #F92672">=</span><span style="color: #F8F8F2"> {price: </span><span style="color: #AE81FF">40</span><span style="color: #F8F8F2">}</span></span>
<span class="line"></span>
<span class="line"><span style="color: #66D9EF; font-style: italic">function</span><span style="color: #F8F8F2"> </span><span style="color: #A6E22E">m1</span><span style="color: #F8F8F2">(</span><span style="color: #FD971F; font-style: italic">obj</span><span style="color: #F8F8F2">,</span><span style="color: #FD971F; font-style: italic">count</span><span style="color: #F8F8F2">){</span></span>
<span class="line"><span style="color: #F8F8F2">  </span><span style="color: #F92672">return</span><span style="color: #F8F8F2"> obj.price </span><span style="color: #F92672">*</span><span style="color: #F8F8F2"> count;</span></span>
<span class="line"><span style="color: #F8F8F2">}</span></span>
<span class="line"><span style="color: #66D9EF; font-style: italic">function</span><span style="color: #F8F8F2"> </span><span style="color: #A6E22E">m2</span><span style="color: #F8F8F2">(</span><span style="color: #FD971F; font-style: italic">obj</span><span style="color: #F8F8F2">,</span><span style="color: #FD971F; font-style: italic">count</span><span style="color: #F8F8F2">){ </span></span>
<span class="line"><span style="color: #F8F8F2">  obj.price </span><span style="color: #F92672">=</span><span style="color: #F8F8F2"> </span><span style="color: #AE81FF">50</span><span style="color: #F8F8F2">; </span><span style="color: #88846F">// 修改了bag对象的属性,不是一个纯函数</span></span>
<span class="line"><span style="color: #F8F8F2">  </span><span style="color: #F92672">return</span><span style="color: #F8F8F2"> obj.price </span><span style="color: #F92672">*</span><span style="color: #F8F8F2"> count</span></span>
<span class="line"><span style="color: #F8F8F2">}</span></span>
<span class="line"><span style="color: #F8F8F2">console.</span><span style="color: #A6E22E">log</span><span style="color: #F8F8F2">(</span><span style="color: #A6E22E">m1</span><span style="color: #F8F8F2">(bag,</span><span style="color: #AE81FF">10</span><span style="color: #F8F8F2">)) </span><span style="color: #88846F">// 400</span></span>
<span class="line"><span style="color: #F8F8F2">console.</span><span style="color: #A6E22E">log</span><span style="color: #F8F8F2">(</span><span style="color: #A6E22E">m2</span><span style="color: #F8F8F2">(bag,</span><span style="color: #AE81FF">10</span><span style="color: #F8F8F2">));  </span><span style="color: #88846F">// 500</span></span>
<span class="line"></span></code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="纯函数的优势" tabindex="-1"><a class="header-anchor" href="#纯函数的优势" aria-hidden="true">#</a> 纯函数的优势</h3>
<p>可以缓存结果:当一个函数的计算非常耗时,如果某个计算结果需要多次使用,那么可以将计算结果缓存,当需要的时候
从缓存中读取数据即可。</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="shiki" style="background-color: #272822"><code><span class="line"><span style="color: #88846F">// 以求圆的面积为例: 不使用缓存</span></span>
<span class="line"><span style="color: #66D9EF; font-style: italic">function</span><span style="color: #F8F8F2"> </span><span style="color: #A6E22E">getArea</span><span style="color: #F8F8F2">(</span><span style="color: #FD971F; font-style: italic">r</span><span style="color: #F8F8F2">){</span></span>
<span class="line"><span style="color: #F8F8F2">  console.</span><span style="color: #A6E22E">log</span><span style="color: #F8F8F2">(</span><span style="color: #E6DB74">&#39;r:&#39;</span><span style="color: #F8F8F2">, r);</span></span>
<span class="line"><span style="color: #F8F8F2">  </span><span style="color: #F92672">return</span><span style="color: #F8F8F2"> </span><span style="color: #66D9EF">Math</span><span style="color: #F8F8F2">.</span><span style="color: #66D9EF">PI</span><span style="color: #F8F8F2"> </span><span style="color: #F92672">*</span><span style="color: #F8F8F2"> r </span><span style="color: #F92672">*</span><span style="color: #F8F8F2"> r;</span></span>
<span class="line"><span style="color: #F8F8F2">}</span></span>
<span class="line"><span style="color: #F8F8F2">console.</span><span style="color: #A6E22E">log</span><span style="color: #F8F8F2">(</span><span style="color: #A6E22E">getArea</span><span style="color: #F8F8F2">(</span><span style="color: #AE81FF">4</span><span style="color: #F8F8F2">));</span></span>
<span class="line"><span style="color: #F8F8F2">console.</span><span style="color: #A6E22E">log</span><span style="color: #F8F8F2">(</span><span style="color: #A6E22E">getArea</span><span style="color: #F8F8F2">(</span><span style="color: #AE81FF">4</span><span style="color: #F8F8F2">));</span></span>
<span class="line"><span style="color: #88846F">/* 因为计算结果没有缓存计算结果, 以上调用会依次输出</span></span>
<span class="line"><span style="color: #88846F">  r: 4</span></span>
<span class="line"><span style="color: #88846F">  50.26548245743669</span></span>
<span class="line"><span style="color: #88846F">  r: 4</span></span>
<span class="line"><span style="color: #88846F">  50.26548245743669</span></span>
<span class="line"><span style="color: #88846F">*/</span></span>
<span class="line"></span></code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>下面实现一个缓存函数,该缓存函数是一个高阶函数,将输输入的键名为输入的参数(因为相同的输入会有相同的输出),计算结果作为键值。</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="shiki" style="background-color: #272822"><code><span class="line"><span style="color: #66D9EF; font-style: italic">function</span><span style="color: #F8F8F2"> </span><span style="color: #A6E22E">memorize</span><span style="color: #F8F8F2">(</span><span style="color: #FD971F; font-style: italic">fun</span><span style="color: #F8F8F2">) {</span></span>
<span class="line"><span style="color: #F8F8F2">  </span><span style="color: #66D9EF; font-style: italic">const</span><span style="color: #F8F8F2"> cache </span><span style="color: #F92672">=</span><span style="color: #F8F8F2"> </span><span style="color: #66D9EF; font-style: italic">Object</span><span style="color: #F8F8F2">.</span><span style="color: #A6E22E">create</span><span style="color: #F8F8F2">(</span><span style="color: #AE81FF">null</span><span style="color: #F8F8F2">); </span><span style="color: #88846F">// 存储计算结果的对象</span></span>
<span class="line"><span style="color: #F8F8F2">  </span><span style="color: #F92672">return</span><span style="color: #F8F8F2"> </span><span style="color: #66D9EF; font-style: italic">function</span><span style="color: #F8F8F2">() {</span></span>
<span class="line"><span style="color: #F8F8F2">    </span><span style="color: #66D9EF; font-style: italic">const</span><span style="color: #F8F8F2"> key </span><span style="color: #F92672">=</span><span style="color: #F8F8F2"> </span><span style="color: #66D9EF">JSON</span><span style="color: #F8F8F2">.</span><span style="color: #66D9EF">stringify</span><span style="color: #F8F8F2">([</span><span style="color: #F92672">...</span><span style="color: #FD971F">arguments</span><span style="color: #F8F8F2">])</span></span>
<span class="line"><span style="color: #F8F8F2">    cache[key] </span><span style="color: #F92672">=</span><span style="color: #F8F8F2"> cache[key] </span><span style="color: #F92672">||</span><span style="color: #F8F8F2"> fun.</span><span style="color: #A6E22E">apply</span><span style="color: #F8F8F2">(</span><span style="color: #AE81FF">null</span><span style="color: #F8F8F2">,[</span><span style="color: #F92672">...</span><span style="color: #FD971F">arguments</span><span style="color: #F8F8F2">])</span></span>
<span class="line"><span style="color: #F8F8F2">    </span><span style="color: #F92672">return</span><span style="color: #F8F8F2"> cache[key]</span></span>
<span class="line"><span style="color: #F8F8F2">  }</span></span>
<span class="line"><span style="color: #F8F8F2">}</span></span>
<span class="line"><span style="color: #66D9EF; font-style: italic">const</span><span style="color: #F8F8F2"> f </span><span style="color: #F92672">=</span><span style="color: #F8F8F2"> </span><span style="color: #A6E22E">memorize</span><span style="color: #F8F8F2">(getArea)</span></span>
<span class="line"><span style="color: #F8F8F2">console.</span><span style="color: #A6E22E">log</span><span style="color: #F8F8F2">(</span><span style="color: #A6E22E">f</span><span style="color: #F8F8F2">(</span><span style="color: #AE81FF">4</span><span style="color: #F8F8F2">))</span></span>
<span class="line"><span style="color: #F8F8F2">console.</span><span style="color: #A6E22E">log</span><span style="color: #F8F8F2">(</span><span style="color: #A6E22E">f</span><span style="color: #F8F8F2">(</span><span style="color: #AE81FF">4</span><span style="color: #F8F8F2">))</span></span>
<span class="line"><span style="color: #88846F">/* 输出结果为, 只执行了一次计算的过程</span></span>
<span class="line"><span style="color: #88846F">r: 4</span></span>
<span class="line"><span style="color: #88846F">50.26548245743669</span></span>
<span class="line"><span style="color: #88846F">50.26548245743669</span></span>
<span class="line"><span style="color: #88846F">*/</span></span>
<span class="line"></span></code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="function-currying" tabindex="-1"><a class="header-anchor" href="#function-currying" aria-hidden="true">#</a> Function Currying</h2>
<p>函数柯里化(currying) 是把接收多个参数的函数 转换为接收一个单一参数(通常这个参数不变)的函数,并返回接收剩余参数的函数。
(将接收n个参数的函数变成只接收1个参数的函数)</p>
<p>比如计算一个数的平方 或者计算 三次方</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="shiki" style="background-color: #272822"><code><span class="line"><span style="color: #66D9EF">Math</span><span style="color: #F8F8F2">.</span><span style="color: #66D9EF">pow</span><span style="color: #F8F8F2">(</span><span style="color: #AE81FF">5</span><span style="color: #F8F8F2">,</span><span style="color: #AE81FF">2</span><span style="color: #F8F8F2">)</span></span>
<span class="line"><span style="color: #66D9EF">Math</span><span style="color: #F8F8F2">.</span><span style="color: #66D9EF">pow</span><span style="color: #F8F8F2">(</span><span style="color: #AE81FF">6</span><span style="color: #F8F8F2">,</span><span style="color: #AE81FF">2</span><span style="color: #F8F8F2">) </span></span>
<span class="line"><span style="color: #88846F">// 每次都要书写Math.pow 和 第二个参数 2, 这里可以认为是重复的书写代码</span></span>
<span class="line"></span>
<span class="line"><span style="color: #66D9EF; font-style: italic">function</span><span style="color: #F8F8F2"> </span><span style="color: #A6E22E">getPower</span><span style="color: #F8F8F2">(</span><span style="color: #FD971F; font-style: italic">x</span><span style="color: #F8F8F2">) { </span><span style="color: #88846F">// 将上面的函数进行改造</span></span>
<span class="line"><span style="color: #F8F8F2">  </span><span style="color: #F92672">return</span><span style="color: #F8F8F2"> </span><span style="color: #66D9EF; font-style: italic">function</span><span style="color: #F8F8F2">(</span><span style="color: #FD971F; font-style: italic">y</span><span style="color: #F8F8F2">){</span></span>
<span class="line"><span style="color: #F8F8F2">    </span><span style="color: #F92672">return</span><span style="color: #F8F8F2"> </span><span style="color: #66D9EF">Math</span><span style="color: #F8F8F2">.</span><span style="color: #66D9EF">pow</span><span style="color: #F8F8F2">(y,x)</span></span>
<span class="line"><span style="color: #F8F8F2">  }</span></span>
<span class="line"><span style="color: #F8F8F2">}</span></span>
<span class="line"><span style="color: #66D9EF; font-style: italic">const</span><span style="color: #F8F8F2"> pow2 </span><span style="color: #F92672">=</span><span style="color: #F8F8F2"> </span><span style="color: #A6E22E">getPower</span><span style="color: #F8F8F2">(</span><span style="color: #AE81FF">2</span><span style="color: #F8F8F2">)  </span><span style="color: #88846F">// 计算二次方</span></span>
<span class="line"><span style="color: #66D9EF; font-style: italic">const</span><span style="color: #F8F8F2"> pow3 </span><span style="color: #F92672">=</span><span style="color: #F8F8F2"> </span><span style="color: #A6E22E">getPower</span><span style="color: #F8F8F2">(</span><span style="color: #AE81FF">3</span><span style="color: #F8F8F2">)  </span><span style="color: #88846F">// 计算三次方</span></span>
<span class="line"></span>
<span class="line"><span style="color: #F8F8F2">console.</span><span style="color: #A6E22E">log</span><span style="color: #F8F8F2">(</span><span style="color: #A6E22E">pow2</span><span style="color: #F8F8F2">(</span><span style="color: #AE81FF">5</span><span style="color: #F8F8F2">))  </span><span style="color: #88846F">// 25</span></span>
<span class="line"><span style="color: #F8F8F2">console.</span><span style="color: #A6E22E">log</span><span style="color: #F8F8F2">(</span><span style="color: #A6E22E">pow2</span><span style="color: #F8F8F2">(</span><span style="color: #AE81FF">6</span><span style="color: #F8F8F2">))  </span><span style="color: #88846F">// 36</span></span>
<span class="line"><span style="color: #F8F8F2">console.</span><span style="color: #A6E22E">log</span><span style="color: #F8F8F2">(</span><span style="color: #A6E22E">pow3</span><span style="color: #F8F8F2">(</span><span style="color: #AE81FF">10</span><span style="color: #F8F8F2">)) </span><span style="color: #88846F">// 1000</span></span>
<span class="line"></span></code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><div class="language-typescript ext-ts line-numbers-mode"><pre v-pre class="shiki" style="background-color: #272822"><code><span class="line"><span style="color: #88846F">// --------- 获取值的准确类型 --------</span></span>
<span class="line"><span style="color: #66D9EF; font-style: italic">const</span><span style="color: #F8F8F2"> s </span><span style="color: #F92672">=</span><span style="color: #F8F8F2"> </span><span style="color: #E6DB74">&#39;123&#39;</span></span>
<span class="line"><span style="color: #66D9EF; font-style: italic">const</span><span style="color: #F8F8F2"> n </span><span style="color: #F92672">=</span><span style="color: #F8F8F2"> </span><span style="color: #AE81FF">123</span></span>
<span class="line"><span style="color: #66D9EF; font-style: italic">const</span><span style="color: #F8F8F2"> b </span><span style="color: #F92672">=</span><span style="color: #F8F8F2"> </span><span style="color: #AE81FF">true</span></span>
<span class="line"><span style="color: #66D9EF; font-style: italic">const</span><span style="color: #F8F8F2"> </span><span style="color: #A6E22E">f</span><span style="color: #F8F8F2"> </span><span style="color: #F92672">=</span><span style="color: #F8F8F2"> () </span><span style="color: #66D9EF; font-style: italic">=&gt;</span><span style="color: #F8F8F2"> {}</span></span>
<span class="line"><span style="color: #66D9EF; font-style: italic">const</span><span style="color: #F8F8F2"> r </span><span style="color: #F92672">=</span><span style="color: #E6DB74"> /</span><span style="color: #AE81FF">\d</span><span style="color: #F92672">+</span><span style="color: #E6DB74">/</span><span style="color: #F92672">g</span><span style="color: #F8F8F2">;</span></span>
<span class="line"><span style="color: #66D9EF; font-style: italic">const</span><span style="color: #F8F8F2"> d </span><span style="color: #F92672">=</span><span style="color: #F8F8F2"> </span><span style="color: #F92672">new</span><span style="color: #F8F8F2"> </span><span style="color: #66D9EF; font-style: italic">Date</span><span style="color: #F8F8F2">()</span></span>
<span class="line"><span style="color: #66D9EF; font-style: italic">const</span><span style="color: #F8F8F2"> u </span><span style="color: #F92672">=</span><span style="color: #F8F8F2"> </span><span style="color: #AE81FF">undefined</span></span>
<span class="line"><span style="color: #66D9EF; font-style: italic">const</span><span style="color: #F8F8F2"> n1 </span><span style="color: #F92672">=</span><span style="color: #F8F8F2"> </span><span style="color: #AE81FF">null</span></span>
<span class="line"><span style="color: #66D9EF; font-style: italic">const</span><span style="color: #F8F8F2"> s1 </span><span style="color: #F92672">=</span><span style="color: #F8F8F2"> </span><span style="color: #66D9EF; font-style: italic">Symbol</span><span style="color: #F8F8F2">(</span><span style="color: #E6DB74">&#39;foo&#39;</span><span style="color: #F8F8F2">)</span></span>
<span class="line"><span style="color: #66D9EF; font-style: italic">const</span><span style="color: #F8F8F2"> s2 </span><span style="color: #F92672">=</span><span style="color: #F8F8F2"> </span><span style="color: #F92672">new</span><span style="color: #F8F8F2"> </span><span style="color: #66D9EF; font-style: italic">Set</span><span style="color: #F8F8F2">()</span></span>
<span class="line"><span style="color: #66D9EF; font-style: italic">const</span><span style="color: #F8F8F2"> m </span><span style="color: #F92672">=</span><span style="color: #F8F8F2"> </span><span style="color: #F92672">new</span><span style="color: #F8F8F2"> </span><span style="color: #66D9EF; font-style: italic">Map</span><span style="color: #F8F8F2">()</span></span>
<span class="line"><span style="color: #66D9EF; font-style: italic">const</span><span style="color: #F8F8F2"> o </span><span style="color: #F92672">=</span><span style="color: #F8F8F2"> {a:</span><span style="color: #AE81FF">1</span><span style="color: #F8F8F2">}</span></span>
<span class="line"><span style="color: #66D9EF; font-style: italic">const</span><span style="color: #F8F8F2"> a </span><span style="color: #F92672">=</span><span style="color: #F8F8F2"> [</span><span style="color: #AE81FF">1</span><span style="color: #F8F8F2">,</span><span style="color: #AE81FF">2</span><span style="color: #F8F8F2">,</span><span style="color: #AE81FF">3</span><span style="color: #F8F8F2">]</span></span>
<span class="line"></span>
<span class="line"><span style="color: #F92672">typeof</span><span style="color: #F8F8F2"> s  </span><span style="color: #88846F">// string</span></span>
<span class="line"><span style="color: #F92672">typeof</span><span style="color: #F8F8F2"> n  </span><span style="color: #88846F">// number</span></span>
<span class="line"><span style="color: #F92672">typeof</span><span style="color: #F8F8F2"> b  </span><span style="color: #88846F">// boolean</span></span>
<span class="line"><span style="color: #F92672">typeof</span><span style="color: #F8F8F2"> f  </span><span style="color: #88846F">// function</span></span>
<span class="line"><span style="color: #F92672">typeof</span><span style="color: #F8F8F2"> r  </span><span style="color: #88846F">// object</span></span>
<span class="line"><span style="color: #F92672">typeof</span><span style="color: #F8F8F2"> d  </span><span style="color: #88846F">// object</span></span>
<span class="line"><span style="color: #F92672">typeof</span><span style="color: #F8F8F2"> u  </span><span style="color: #88846F">// undefined</span></span>
<span class="line"><span style="color: #F92672">typeof</span><span style="color: #F8F8F2"> n1 </span><span style="color: #88846F">// object</span></span>
<span class="line"><span style="color: #F92672">typeof</span><span style="color: #F8F8F2"> s1 </span><span style="color: #88846F">// symbol</span></span>
<span class="line"><span style="color: #F92672">typeof</span><span style="color: #F8F8F2"> o  </span><span style="color: #88846F">// object</span></span>
<span class="line"><span style="color: #F92672">typeof</span><span style="color: #F8F8F2"> a  </span><span style="color: #88846F">// object</span></span>
<span class="line"><span style="color: #F92672">typeof</span><span style="color: #F8F8F2"> s2 </span><span style="color: #88846F">// object</span></span>
<span class="line"><span style="color: #F92672">typeof</span><span style="color: #F8F8F2"> m  </span><span style="color: #88846F">// object</span></span>
<span class="line"></span>
<span class="line"><span style="color: #88846F">// typeof判断值的类型有缺陷, 只能判断值类型， 其他就是 function / object</span></span>
<span class="line"></span>
<span class="line"><span style="color: #66D9EF; font-style: italic">function</span><span style="color: #F8F8F2"> </span><span style="color: #A6E22E">getType</span><span style="color: #F8F8F2">(</span><span style="color: #FD971F; font-style: italic">data</span><span style="color: #F92672">:</span><span style="color: #66D9EF; font-style: italic">any</span><span style="color: #F8F8F2">)</span><span style="color: #F92672">:</span><span style="color: #F8F8F2"> </span><span style="color: #66D9EF; font-style: italic">string</span><span style="color: #F8F8F2"> { </span><span style="color: #88846F">// [object ]</span></span>
<span class="line"><span style="color: #F8F8F2">  </span><span style="color: #F92672">return</span><span style="color: #F8F8F2"> </span><span style="color: #66D9EF; font-style: italic">Object</span><span style="color: #F8F8F2">.prototype.toString.</span><span style="color: #A6E22E">call</span><span style="color: #F8F8F2">(data).</span><span style="color: #A6E22E">slice</span><span style="color: #F8F8F2">(</span><span style="color: #AE81FF">8</span><span style="color: #F8F8F2">, </span><span style="color: #F92672">-</span><span style="color: #AE81FF">1</span><span style="color: #F8F8F2">).</span><span style="color: #A6E22E">toLowerCase</span><span style="color: #F8F8F2">()</span></span>
<span class="line"><span style="color: #F8F8F2">}</span></span>
<span class="line"><span style="color: #A6E22E">getType</span><span style="color: #F8F8F2">(s) </span><span style="color: #88846F">// string</span></span>
<span class="line"><span style="color: #A6E22E">getType</span><span style="color: #F8F8F2">(n) </span><span style="color: #88846F">// number</span></span>
<span class="line"><span style="color: #A6E22E">getType</span><span style="color: #F8F8F2">(b) </span><span style="color: #88846F">// boolean</span></span>
<span class="line"><span style="color: #A6E22E">getType</span><span style="color: #F8F8F2">(f) </span><span style="color: #88846F">// function</span></span>
<span class="line"><span style="color: #A6E22E">getType</span><span style="color: #F8F8F2">(r) </span><span style="color: #88846F">// regexp</span></span>
<span class="line"><span style="color: #A6E22E">getType</span><span style="color: #F8F8F2">(d) </span><span style="color: #88846F">// date</span></span>
<span class="line"><span style="color: #A6E22E">getType</span><span style="color: #F8F8F2">(u) </span><span style="color: #88846F">// undefined</span></span>
<span class="line"><span style="color: #A6E22E">getType</span><span style="color: #F8F8F2">(n1)  </span><span style="color: #88846F">// null</span></span>
<span class="line"><span style="color: #A6E22E">getType</span><span style="color: #F8F8F2">(s1)  </span><span style="color: #88846F">// symbol</span></span>
<span class="line"><span style="color: #A6E22E">getType</span><span style="color: #F8F8F2">(o) </span><span style="color: #88846F">// object</span></span>
<span class="line"><span style="color: #A6E22E">getType</span><span style="color: #F8F8F2">(a) </span><span style="color: #88846F">// array</span></span>
<span class="line"><span style="color: #A6E22E">getType</span><span style="color: #F8F8F2">(s2)  </span><span style="color: #88846F">// set</span></span>
<span class="line"><span style="color: #A6E22E">getType</span><span style="color: #F8F8F2">(m) </span><span style="color: #88846F">// map</span></span>
<span class="line"></span>
<span class="line"><span style="color: #88846F">// --------- 利用函数柯里化, 判断某个值是不是指定的类型 ---------</span></span>
<span class="line"><span style="color: #66D9EF; font-style: italic">function</span><span style="color: #F8F8F2"> </span><span style="color: #A6E22E">isType</span><span style="color: #F8F8F2">(</span><span style="color: #FD971F; font-style: italic">type</span><span style="color: #F92672">:</span><span style="color: #F8F8F2"> </span><span style="color: #66D9EF; font-style: italic">string</span><span style="color: #F8F8F2">)</span><span style="color: #F92672">:</span><span style="color: #F8F8F2">(</span><span style="color: #FD971F; font-style: italic">data</span><span style="color: #F92672">:</span><span style="color: #F8F8F2"> </span><span style="color: #66D9EF; font-style: italic">any</span><span style="color: #F8F8F2">) </span><span style="color: #66D9EF; font-style: italic">=&gt;</span><span style="color: #F8F8F2"> </span><span style="color: #66D9EF; font-style: italic">boolean</span><span style="color: #F8F8F2"> {</span></span>
<span class="line"><span style="color: #F8F8F2">  </span><span style="color: #F92672">return</span><span style="color: #F8F8F2"> </span><span style="color: #66D9EF; font-style: italic">function</span><span style="color: #F8F8F2">(</span><span style="color: #FD971F; font-style: italic">object</span><span style="color: #F8F8F2">) {</span></span>
<span class="line"><span style="color: #F8F8F2">    </span><span style="color: #F92672">return</span><span style="color: #F8F8F2"> </span><span style="color: #66D9EF; font-style: italic">Object</span><span style="color: #F8F8F2">.prototype.toString.</span><span style="color: #A6E22E">call</span><span style="color: #F8F8F2">(object) </span><span style="color: #F92672">===</span><span style="color: #F8F8F2"> </span><span style="color: #E6DB74">`[object </span><span style="color: #F92672">${</span><span style="color: #F8F8F2">type</span><span style="color: #F92672">}</span><span style="color: #E6DB74">]`</span></span>
<span class="line"><span style="color: #F8F8F2">  }</span></span>
<span class="line"><span style="color: #F8F8F2">}</span></span>
<span class="line"><span style="color: #66D9EF; font-style: italic">const</span><span style="color: #F8F8F2"> isString </span><span style="color: #F92672">=</span><span style="color: #F8F8F2"> </span><span style="color: #A6E22E">isType</span><span style="color: #F8F8F2">(</span><span style="color: #E6DB74">&#39;String&#39;</span><span style="color: #F8F8F2">)</span></span>
<span class="line"><span style="color: #F8F8F2">console.</span><span style="color: #A6E22E">log</span><span style="color: #F8F8F2">(</span><span style="color: #A6E22E">isString</span><span style="color: #F8F8F2">(</span><span style="color: #E6DB74">&#39;123&#39;</span><span style="color: #F8F8F2">))  </span><span style="color: #88846F">// true</span></span>
<span class="line"><span style="color: #F8F8F2">console.</span><span style="color: #A6E22E">log</span><span style="color: #F8F8F2">(</span><span style="color: #A6E22E">isString</span><span style="color: #F8F8F2">(</span><span style="color: #AE81FF">123</span><span style="color: #F8F8F2">))    </span><span style="color: #88846F">// false</span></span>
<span class="line"></span></code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>下面实现一个柯里化的封装函数</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="shiki" style="background-color: #272822"><code><span class="line"><span style="color: #66D9EF; font-style: italic">function</span><span style="color: #F8F8F2"> </span><span style="color: #A6E22E">add</span><span style="color: #F8F8F2">(</span><span style="color: #FD971F; font-style: italic">a</span><span style="color: #F8F8F2">,</span><span style="color: #FD971F; font-style: italic">b</span><span style="color: #F8F8F2">,</span><span style="color: #FD971F; font-style: italic">c</span><span style="color: #F8F8F2">,</span><span style="color: #FD971F; font-style: italic">d</span><span style="color: #F8F8F2">){</span></span>
<span class="line"><span style="color: #F8F8F2">  </span><span style="color: #F92672">return</span><span style="color: #F8F8F2"> a </span><span style="color: #F92672">+</span><span style="color: #F8F8F2"> b </span><span style="color: #F92672">+</span><span style="color: #F8F8F2"> c </span><span style="color: #F92672">+</span><span style="color: #F8F8F2"> d</span></span>
<span class="line"><span style="color: #F8F8F2">}</span></span>
<span class="line"><span style="color: #66D9EF; font-style: italic">function</span><span style="color: #F8F8F2"> </span><span style="color: #A6E22E">curry</span><span style="color: #F8F8F2">(</span><span style="color: #FD971F; font-style: italic">fun</span><span style="color: #F8F8F2">){</span></span>
<span class="line"><span style="color: #F8F8F2">  </span><span style="color: #F92672">return</span><span style="color: #F8F8F2"> </span><span style="color: #66D9EF; font-style: italic">function</span><span style="color: #F8F8F2">(</span><span style="color: #F92672">...</span><span style="color: #FD971F; font-style: italic">args</span><span style="color: #F8F8F2">) {</span></span>
<span class="line"><span style="color: #F8F8F2">    </span><span style="color: #F92672">return</span><span style="color: #F8F8F2"> </span><span style="color: #66D9EF; font-style: italic">function</span><span style="color: #F8F8F2">(){</span></span>
<span class="line"><span style="color: #F8F8F2">      </span><span style="color: #66D9EF; font-style: italic">const</span><span style="color: #F8F8F2"> arr </span><span style="color: #F92672">=</span><span style="color: #F8F8F2"> [</span><span style="color: #F92672">...</span><span style="color: #F8F8F2">args,</span><span style="color: #F92672">...</span><span style="color: #FD971F">arguments</span><span style="color: #F8F8F2">]</span></span>
<span class="line"><span style="color: #F8F8F2">      </span><span style="color: #F92672">return</span><span style="color: #F8F8F2"> fun.</span><span style="color: #A6E22E">apply</span><span style="color: #F8F8F2">(</span><span style="color: #AE81FF">null</span><span style="color: #F8F8F2">,[</span><span style="color: #F92672">...</span><span style="color: #F8F8F2">arr])</span></span>
<span class="line"><span style="color: #F8F8F2">    }</span></span>
<span class="line"><span style="color: #F8F8F2">  }</span></span>
<span class="line"><span style="color: #F8F8F2">}</span></span>
<span class="line"><span style="color: #66D9EF; font-style: italic">const</span><span style="color: #F8F8F2"> c_add </span><span style="color: #F92672">=</span><span style="color: #F8F8F2"> </span><span style="color: #A6E22E">curry</span><span style="color: #F8F8F2">(add)</span></span>
<span class="line"><span style="color: #A6E22E">c_add</span><span style="color: #F8F8F2">(</span><span style="color: #AE81FF">1</span><span style="color: #F8F8F2">,</span><span style="color: #AE81FF">2</span><span style="color: #F8F8F2">)(</span><span style="color: #AE81FF">3</span><span style="color: #F8F8F2">,</span><span style="color: #AE81FF">4</span><span style="color: #F8F8F2">)  </span><span style="color: #88846F">// 10</span></span>
<span class="line"><span style="color: #A6E22E">c_add</span><span style="color: #F8F8F2">(</span><span style="color: #AE81FF">1</span><span style="color: #F8F8F2">,</span><span style="color: #AE81FF">2</span><span style="color: #F8F8F2">,</span><span style="color: #AE81FF">3</span><span style="color: #F8F8F2">)(</span><span style="color: #AE81FF">4</span><span style="color: #F8F8F2">) </span><span style="color: #88846F">// 10</span></span>
<span class="line"><span style="color: #A6E22E">c_add</span><span style="color: #F8F8F2">(</span><span style="color: #AE81FF">1</span><span style="color: #F8F8F2">)(</span><span style="color: #AE81FF">2</span><span style="color: #F8F8F2">,</span><span style="color: #AE81FF">3</span><span style="color: #F8F8F2">,</span><span style="color: #AE81FF">4</span><span style="color: #F8F8F2">)  </span><span style="color: #88846F">// 10</span></span>
<span class="line"></span></code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>首先获取一部分参数,然后通过将剩余参数收集起来合并,一起传递给被柯里化的函数作为参数。上面的封装在有些情况下可以解决一部分问题。
但是只能多扩展一个参数, curry(a)(b)(c) 这样多调用就不支持了。所以对上面的封装做一层改进:</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="shiki" style="background-color: #272822"><code><span class="line"><span style="color: #66D9EF; font-style: italic">function</span><span style="color: #F8F8F2"> </span><span style="color: #A6E22E">sum</span><span style="color: #F8F8F2">(</span><span style="color: #FD971F; font-style: italic">a</span><span style="color: #F8F8F2">,</span><span style="color: #FD971F; font-style: italic">b</span><span style="color: #F8F8F2">,</span><span style="color: #FD971F; font-style: italic">c</span><span style="color: #F8F8F2">,</span><span style="color: #FD971F; font-style: italic">d</span><span style="color: #F8F8F2">){</span></span>
<span class="line"><span style="color: #F8F8F2">  </span><span style="color: #F92672">return</span><span style="color: #F8F8F2"> a </span><span style="color: #F92672">+</span><span style="color: #F8F8F2"> b </span><span style="color: #F92672">+</span><span style="color: #F8F8F2"> c </span><span style="color: #F92672">+</span><span style="color: #F8F8F2"> d</span></span>
<span class="line"><span style="color: #F8F8F2">}</span></span>
<span class="line"></span>
<span class="line"><span style="color: #66D9EF; font-style: italic">function</span><span style="color: #F8F8F2"> </span><span style="color: #A6E22E">curry</span><span style="color: #F8F8F2">(</span><span style="color: #FD971F; font-style: italic">fun</span><span style="color: #F8F8F2">) {  </span></span>
<span class="line"><span style="color: #F8F8F2">  </span><span style="color: #88846F">// fun为传递的参数, fun.length为函数的参数个数, ...args为返回的函数接收的参数</span></span>
<span class="line"><span style="color: #F8F8F2">  </span><span style="color: #F92672">return</span><span style="color: #F8F8F2"> </span><span style="color: #66D9EF; font-style: italic">function</span><span style="color: #F8F8F2"> </span><span style="color: #A6E22E">curriedFun</span><span style="color: #F8F8F2">(</span><span style="color: #F92672">...</span><span style="color: #FD971F; font-style: italic">args</span><span style="color: #F8F8F2">) {</span></span>
<span class="line"><span style="color: #F8F8F2">    </span><span style="color: #88846F">// 如果被柯里化的函数的参数个数大于第一次接收的参数个数,则还需要接收剩下的参数</span></span>
<span class="line"><span style="color: #F8F8F2">    </span><span style="color: #F92672">if</span><span style="color: #F8F8F2">(args.length </span><span style="color: #F92672">&lt;</span><span style="color: #F8F8F2"> fun.length) { </span></span>
<span class="line"><span style="color: #F8F8F2">      </span><span style="color: #F92672">return</span><span style="color: #F8F8F2"> </span><span style="color: #66D9EF; font-style: italic">function</span><span style="color: #F8F8F2">() { </span><span style="color: #88846F">// ...arguments接收剩下的参数</span></span>
<span class="line"><span style="color: #F8F8F2">        </span><span style="color: #88846F">// 将所有参数合并 接着传递给curriedFun,再次判断所有参数是否与被柯里化的函数的参数个数相等</span></span>
<span class="line"><span style="color: #F8F8F2">        </span><span style="color: #66D9EF; font-style: italic">const</span><span style="color: #F8F8F2"> arr </span><span style="color: #F92672">=</span><span style="color: #F8F8F2"> [</span><span style="color: #F92672">...</span><span style="color: #F8F8F2">args,</span><span style="color: #F92672">...</span><span style="color: #FD971F">arguments</span><span style="color: #F8F8F2">]  </span></span>
<span class="line"><span style="color: #F8F8F2">        </span><span style="color: #F92672">return</span><span style="color: #F8F8F2"> </span><span style="color: #A6E22E">curriedFun</span><span style="color: #F8F8F2">(</span><span style="color: #F92672">...</span><span style="color: #F8F8F2">arr)</span></span>
<span class="line"><span style="color: #F8F8F2">      }</span></span>
<span class="line"><span style="color: #F8F8F2">    }</span></span>
<span class="line"><span style="color: #F8F8F2">    </span><span style="color: #F92672">return</span><span style="color: #F8F8F2"> </span><span style="color: #A6E22E">fun</span><span style="color: #F8F8F2">(</span><span style="color: #F92672">...</span><span style="color: #F8F8F2">args)</span></span>
<span class="line"><span style="color: #F8F8F2">  }</span></span>
<span class="line"><span style="color: #F8F8F2">}</span></span>
<span class="line"><span style="color: #66D9EF; font-style: italic">const</span><span style="color: #F8F8F2"> add </span><span style="color: #F92672">=</span><span style="color: #F8F8F2"> </span><span style="color: #A6E22E">curry</span><span style="color: #F8F8F2">(sum);</span></span>
<span class="line"><span style="color: #A6E22E">add</span><span style="color: #F8F8F2">(</span><span style="color: #AE81FF">1</span><span style="color: #F8F8F2">)(</span><span style="color: #AE81FF">2</span><span style="color: #F8F8F2">)(</span><span style="color: #AE81FF">3</span><span style="color: #F8F8F2">)(</span><span style="color: #AE81FF">4</span><span style="color: #F8F8F2">) </span><span style="color: #88846F">// 10</span></span>
<span class="line"><span style="color: #A6E22E">add</span><span style="color: #F8F8F2">(</span><span style="color: #AE81FF">1</span><span style="color: #F8F8F2">,</span><span style="color: #AE81FF">2</span><span style="color: #F8F8F2">)(</span><span style="color: #AE81FF">3</span><span style="color: #F8F8F2">,</span><span style="color: #AE81FF">4</span><span style="color: #F8F8F2">) </span><span style="color: #88846F">// 10</span></span>
<span class="line"><span style="color: #A6E22E">add</span><span style="color: #F8F8F2">(</span><span style="color: #AE81FF">1</span><span style="color: #F8F8F2">)(</span><span style="color: #AE81FF">2</span><span style="color: #F8F8F2">)(</span><span style="color: #AE81FF">3</span><span style="color: #F8F8F2">,</span><span style="color: #AE81FF">4</span><span style="color: #F8F8F2">)  </span><span style="color: #88846F">// 10</span></span>
<span class="line"><span style="color: #A6E22E">add</span><span style="color: #F8F8F2">(</span><span style="color: #AE81FF">1</span><span style="color: #F8F8F2">,</span><span style="color: #AE81FF">2</span><span style="color: #F8F8F2">,</span><span style="color: #AE81FF">3</span><span style="color: #F8F8F2">,</span><span style="color: #AE81FF">4</span><span style="color: #F8F8F2">)  </span><span style="color: #88846F">// 10</span></span>
<span class="line"></span>
<span class="line"></span>
<span class="line"><span style="color: #88846F">// ------ 另一种收集函数参数的方法 --------</span></span>
<span class="line"><span style="color: #66D9EF; font-style: italic">function</span><span style="color: #F8F8F2"> </span><span style="color: #A6E22E">curry</span><span style="color: #F8F8F2">(</span><span style="color: #FD971F; font-style: italic">fn</span><span style="color: #F8F8F2">) {</span></span>
<span class="line"><span style="color: #F8F8F2">  </span><span style="color: #66D9EF; font-style: italic">const</span><span style="color: #F8F8F2"> argsLength </span><span style="color: #F92672">=</span><span style="color: #F8F8F2"> fn.length</span></span>
<span class="line"><span style="color: #F8F8F2">  </span><span style="color: #66D9EF; font-style: italic">let</span><span style="color: #F8F8F2"> args </span><span style="color: #F92672">=</span><span style="color: #F8F8F2"> []</span></span>
<span class="line"><span style="color: #F8F8F2">  </span><span style="color: #F92672">return</span><span style="color: #F8F8F2"> </span><span style="color: #66D9EF; font-style: italic">function</span><span style="color: #F8F8F2"> </span><span style="color: #A6E22E">f1</span><span style="color: #F8F8F2">() {</span></span>
<span class="line"><span style="color: #F8F8F2">    args </span><span style="color: #F92672">=</span><span style="color: #F8F8F2"> [</span><span style="color: #F92672">...</span><span style="color: #F8F8F2">args, </span><span style="color: #F92672">...</span><span style="color: #FD971F">arguments</span><span style="color: #F8F8F2">]</span></span>
<span class="line"><span style="color: #F8F8F2">    </span><span style="color: #F92672">if</span><span style="color: #F8F8F2">(args.length </span><span style="color: #F92672">&lt;</span><span style="color: #F8F8F2"> argsLength) {</span></span>
<span class="line"><span style="color: #F8F8F2">      </span><span style="color: #F92672">return</span><span style="color: #F8F8F2"> f1</span></span>
<span class="line"><span style="color: #F8F8F2">    }</span></span>
<span class="line"><span style="color: #F8F8F2">    </span><span style="color: #F92672">return</span><span style="color: #F8F8F2"> fn.</span><span style="color: #A6E22E">apply</span><span style="color: #F8F8F2">(</span><span style="color: #FD971F">this</span><span style="color: #F8F8F2">, </span><span style="color: #F92672">...</span><span style="color: #F8F8F2">args)</span></span>
<span class="line"><span style="color: #F8F8F2">  }</span></span>
<span class="line"><span style="color: #F8F8F2">}</span></span>
<span class="line"><span style="color: #66D9EF; font-style: italic">const</span><span style="color: #F8F8F2"> s </span><span style="color: #F92672">=</span><span style="color: #F8F8F2"> </span><span style="color: #A6E22E">curry</span><span style="color: #F8F8F2">(sum)</span></span>
<span class="line"><span style="color: #F8F8F2">console.</span><span style="color: #A6E22E">log</span><span style="color: #F8F8F2">(</span><span style="color: #A6E22E">s</span><span style="color: #F8F8F2">(</span><span style="color: #AE81FF">1</span><span style="color: #F8F8F2">)(</span><span style="color: #AE81FF">2</span><span style="color: #F8F8F2">)(</span><span style="color: #AE81FF">3</span><span style="color: #F8F8F2">)(</span><span style="color: #AE81FF">4</span><span style="color: #F8F8F2">))  </span><span style="color: #88846F">// 10</span></span>
<span class="line"><span style="color: #F8F8F2">console.</span><span style="color: #A6E22E">log</span><span style="color: #F8F8F2">(</span><span style="color: #A6E22E">s</span><span style="color: #F8F8F2">(</span><span style="color: #AE81FF">1</span><span style="color: #F8F8F2">,</span><span style="color: #AE81FF">2</span><span style="color: #F8F8F2">)(</span><span style="color: #AE81FF">3</span><span style="color: #F8F8F2">,</span><span style="color: #AE81FF">4</span><span style="color: #F8F8F2">))   </span><span style="color: #88846F">// 10</span></span>
<span class="line"><span style="color: #F8F8F2">console.</span><span style="color: #A6E22E">log</span><span style="color: #F8F8F2">(</span><span style="color: #A6E22E">s</span><span style="color: #F8F8F2">(</span><span style="color: #AE81FF">1</span><span style="color: #F8F8F2">,</span><span style="color: #AE81FF">2</span><span style="color: #F8F8F2">,</span><span style="color: #AE81FF">3</span><span style="color: #F8F8F2">)(</span><span style="color: #AE81FF">4</span><span style="color: #F8F8F2">))   </span><span style="color: #88846F">// 10</span></span>
<span class="line"></span></code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><div class="custom-container tip"><p class="custom-container-title">TIP</p>
<p>Function.length 指明函数的行参个数, 不包括rest参数</p>
</div>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="shiki" style="background-color: #272822"><code><span class="line"><span style="color: #F8F8F2">(</span><span style="color: #66D9EF; font-style: italic">function</span><span style="color: #F8F8F2"> </span><span style="color: #A6E22E">foo</span><span style="color: #F8F8F2">(</span><span style="color: #FD971F; font-style: italic">a</span><span style="color: #F8F8F2">){}).length      </span><span style="color: #88846F">// 1</span></span>
<span class="line"><span style="color: #F8F8F2">(</span><span style="color: #66D9EF; font-style: italic">function</span><span style="color: #F8F8F2"> </span><span style="color: #A6E22E">foo</span><span style="color: #F8F8F2">(</span><span style="color: #FD971F; font-style: italic">a</span><span style="color: #F8F8F2">,</span><span style="color: #F92672">...</span><span style="color: #FD971F; font-style: italic">b</span><span style="color: #F8F8F2">){}).length </span><span style="color: #88846F">// 1</span></span>
<span class="line"></span></code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="compose-function" tabindex="-1"><a class="header-anchor" href="#compose-function" aria-hidden="true">#</a> Compose Function</h2>
<p>函数柯里化很容易写出洋葱型代码 如 f(g(h(v)),而组合函数可以让我们把细粒度的函数重新组合生成一个新的函数并完成参数的传递.</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="shiki" style="background-color: #272822"><code><span class="line"><span style="color: #66D9EF; font-style: italic">const</span><span style="color: #F8F8F2"> fn </span><span style="color: #F92672">=</span><span style="color: #F8F8F2"> </span><span style="color: #A6E22E">compose</span><span style="color: #F8F8F2">(f1,f2,f3,f4)</span></span>
<span class="line"><span style="color: #A6E22E">fn</span><span style="color: #F8F8F2">(</span><span style="color: #AE81FF">123</span><span style="color: #F8F8F2">)</span></span>
<span class="line"></span></code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><p>下面的例子 通过函数组合的方式实现一个返回数组的最后一个元素</p>
<div class="custom-container tip"><p class="custom-container-title">TIP</p>
<p>(实现这个需求很简单😞 这里只是为了展示组合函数的实现。思路是 先反转数组,然后取数组的第一个元素即可)</p>
</div>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="shiki" style="background-color: #272822"><code><span class="line"><span style="color: #66D9EF; font-style: italic">function</span><span style="color: #F8F8F2"> </span><span style="color: #A6E22E">reverse</span><span style="color: #F8F8F2">(</span><span style="color: #FD971F; font-style: italic">array</span><span style="color: #F8F8F2">){</span></span>
<span class="line"><span style="color: #F8F8F2">  </span><span style="color: #F92672">return</span><span style="color: #F8F8F2"> array.</span><span style="color: #A6E22E">reverse</span><span style="color: #F8F8F2">()</span></span>
<span class="line"><span style="color: #F8F8F2">}</span></span>
<span class="line"><span style="color: #66D9EF; font-style: italic">function</span><span style="color: #F8F8F2"> </span><span style="color: #A6E22E">first</span><span style="color: #F8F8F2">(</span><span style="color: #FD971F; font-style: italic">array</span><span style="color: #F8F8F2">){</span></span>
<span class="line"><span style="color: #F8F8F2">  </span><span style="color: #F92672">return</span><span style="color: #F8F8F2"> array[</span><span style="color: #AE81FF">0</span><span style="color: #F8F8F2">]</span></span>
<span class="line"><span style="color: #F8F8F2">}</span></span>
<span class="line"></span>
<span class="line"><span style="color: #66D9EF; font-style: italic">function</span><span style="color: #F8F8F2"> </span><span style="color: #A6E22E">compose</span><span style="color: #F8F8F2">(</span><span style="color: #FD971F; font-style: italic">f</span><span style="color: #F8F8F2">,</span><span style="color: #FD971F; font-style: italic">g</span><span style="color: #F8F8F2">){  </span><span style="color: #88846F">// 组合函数,参数里的函数从右往左执行</span></span>
<span class="line"><span style="color: #F8F8F2">  </span><span style="color: #F92672">return</span><span style="color: #F8F8F2"> </span><span style="color: #66D9EF; font-style: italic">function</span><span style="color: #F8F8F2">(</span><span style="color: #FD971F; font-style: italic">array</span><span style="color: #F8F8F2">) {</span></span>
<span class="line"><span style="color: #F8F8F2">    </span><span style="color: #F92672">return</span><span style="color: #F8F8F2"> </span><span style="color: #A6E22E">f</span><span style="color: #F8F8F2">(</span><span style="color: #A6E22E">g</span><span style="color: #F8F8F2">(array))</span></span>
<span class="line"><span style="color: #F8F8F2">  }</span></span>
<span class="line"><span style="color: #F8F8F2">}</span></span>
<span class="line"></span>
<span class="line"><span style="color: #66D9EF; font-style: italic">const</span><span style="color: #F8F8F2"> find </span><span style="color: #F92672">=</span><span style="color: #F8F8F2"> </span><span style="color: #A6E22E">compose</span><span style="color: #F8F8F2">(first,reverse)</span></span>
<span class="line"><span style="color: #A6E22E">find</span><span style="color: #F8F8F2">([</span><span style="color: #AE81FF">1</span><span style="color: #F8F8F2">,</span><span style="color: #AE81FF">2</span><span style="color: #F8F8F2">,</span><span style="color: #AE81FF">3</span><span style="color: #F8F8F2">,</span><span style="color: #AE81FF">4</span><span style="color: #F8F8F2">,</span><span style="color: #AE81FF">5</span><span style="color: #F8F8F2">]);  </span><span style="color: #88846F">// 5</span></span>
<span class="line"></span></code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>上面虽然实现了 一个简单的函数组合封装,但和函数柯里化一开始的实现方式一样有一点缺陷,就是只能传递两个函数作为参数。无法
传递多个。下面的封装作为改进,可以接收多个 函数参数</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="shiki" style="background-color: #272822"><code><span class="line"><span style="color: #66D9EF; font-style: italic">function</span><span style="color: #F8F8F2"> </span><span style="color: #A6E22E">compose</span><span style="color: #F8F8F2">(</span><span style="color: #F92672">...</span><span style="color: #FD971F; font-style: italic">args</span><span style="color: #F8F8F2">){</span></span>
<span class="line"><span style="color: #F8F8F2">  </span><span style="color: #66D9EF; font-style: italic">let</span><span style="color: #F8F8F2"> check </span><span style="color: #F92672">=</span><span style="color: #F8F8F2"> args.</span><span style="color: #A6E22E">every</span><span style="color: #F8F8F2">(</span><span style="color: #FD971F; font-style: italic">fn</span><span style="color: #F8F8F2"> </span><span style="color: #66D9EF; font-style: italic">=&gt;</span><span style="color: #F8F8F2"> </span><span style="color: #F92672">typeof</span><span style="color: #F8F8F2"> fn </span><span style="color: #F92672">===</span><span style="color: #F8F8F2"> </span><span style="color: #E6DB74">&#39;function&#39;</span><span style="color: #F8F8F2">)</span></span>
<span class="line"><span style="color: #F8F8F2">  </span><span style="color: #F92672">if</span><span style="color: #F8F8F2">(</span><span style="color: #F92672">!</span><span style="color: #F8F8F2">check) {</span></span>
<span class="line"><span style="color: #F8F8F2">    </span><span style="color: #F92672">throw</span><span style="color: #F8F8F2"> </span><span style="color: #F92672">new</span><span style="color: #F8F8F2"> </span><span style="color: #66D9EF; font-style: italic">Error</span><span style="color: #F8F8F2">(</span><span style="color: #E6DB74">&#39;arguments expected function&#39;</span><span style="color: #F8F8F2">)</span></span>
<span class="line"><span style="color: #F8F8F2">  }</span></span>
<span class="line"><span style="color: #F8F8F2">  </span><span style="color: #F92672">return</span><span style="color: #F8F8F2"> </span><span style="color: #66D9EF; font-style: italic">function</span><span style="color: #F8F8F2">(</span><span style="color: #FD971F; font-style: italic">value</span><span style="color: #F8F8F2">) {</span><span style="color: #88846F">//要处理的数据,默认从右往左执行,然后将执行结果传递给前一个函数</span></span>
<span class="line"><span style="color: #F8F8F2">    </span><span style="color: #F92672">return</span><span style="color: #F8F8F2"> args.reverse.</span><span style="color: #A6E22E">reduce</span><span style="color: #F8F8F2">((</span><span style="color: #FD971F; font-style: italic">acc</span><span style="color: #F8F8F2">,</span><span style="color: #FD971F; font-style: italic">fn</span><span style="color: #F8F8F2">) </span><span style="color: #66D9EF; font-style: italic">=&gt;</span><span style="color: #F8F8F2"> </span><span style="color: #A6E22E">fn</span><span style="color: #F8F8F2">(acc), value)</span></span>
<span class="line"><span style="color: #F8F8F2">  }</span></span>
<span class="line"><span style="color: #F8F8F2">}</span></span>
<span class="line"><span style="color: #88846F">// 再次执行上面的函数</span></span>
<span class="line"><span style="color: #66D9EF; font-style: italic">const</span><span style="color: #F8F8F2"> last </span><span style="color: #F92672">=</span><span style="color: #F8F8F2"> </span><span style="color: #A6E22E">compose</span><span style="color: #F8F8F2">(first,reverse)</span></span>
<span class="line"><span style="color: #A6E22E">last</span><span style="color: #F8F8F2">([</span><span style="color: #AE81FF">1</span><span style="color: #F8F8F2">,</span><span style="color: #AE81FF">2</span><span style="color: #F8F8F2">,</span><span style="color: #AE81FF">3</span><span style="color: #F8F8F2">,</span><span style="color: #AE81FF">4</span><span style="color: #F8F8F2">,</span><span style="color: #AE81FF">5</span><span style="color: #F8F8F2">]) </span><span style="color: #88846F">// 5</span></span>
<span class="line"></span></code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></div></template>
