<template><div><h1 id="排序" tabindex="-1"><a class="header-anchor" href="#排序" aria-hidden="true">#</a> 排序</h1>
<h2 id="快速排序" tabindex="-1"><a class="header-anchor" href="#快速排序" aria-hidden="true">#</a> 快速排序</h2>
<p>流程: 首先假定一个分界值, 通过该分界值将数组分成左右两个部分。将大于或者等于分界值的数放在右边
小于分界值的数放在左边. 然后左右两边的数据可以独立排序.重复上面的操作。</p>
<div class="language-typescript ext-ts line-numbers-mode"><pre v-pre class="shiki" style="background-color: #272822"><code><span class="line"><span style="color: #88846F">// ------ 快速排序 使用splice ---------</span></span>
<span class="line"><span style="color: #66D9EF; font-style: italic">function</span><span style="color: #F8F8F2"> </span><span style="color: #A6E22E">quickSpliceSort</span><span style="color: #F8F8F2">(</span><span style="color: #FD971F; font-style: italic">array</span><span style="color: #F92672">:</span><span style="color: #66D9EF; font-style: italic">number</span><span style="color: #F8F8F2">[])</span><span style="color: #F92672">:</span><span style="color: #F8F8F2"> </span><span style="color: #66D9EF; font-style: italic">number</span><span style="color: #F8F8F2"> [] {</span></span>
<span class="line"><span style="color: #F8F8F2">  </span><span style="color: #66D9EF; font-style: italic">const</span><span style="color: #F8F8F2"> length </span><span style="color: #F92672">=</span><span style="color: #F8F8F2"> array.length;</span></span>
<span class="line"><span style="color: #F8F8F2">  </span><span style="color: #F92672">if</span><span style="color: #F8F8F2">(length </span><span style="color: #F92672">===</span><span style="color: #F8F8F2"> </span><span style="color: #AE81FF">0</span><span style="color: #F8F8F2">) </span><span style="color: #F92672">return</span><span style="color: #F8F8F2"> []</span></span>
<span class="line"><span style="color: #F8F8F2">  </span><span style="color: #66D9EF; font-style: italic">const</span><span style="color: #F8F8F2"> middleIndex </span><span style="color: #F92672">=</span><span style="color: #F8F8F2"> </span><span style="color: #66D9EF">Math</span><span style="color: #F8F8F2">.</span><span style="color: #66D9EF">floor</span><span style="color: #F8F8F2">(length </span><span style="color: #F92672">/</span><span style="color: #F8F8F2"> </span><span style="color: #AE81FF">2</span><span style="color: #F8F8F2">)</span></span>
<span class="line"><span style="color: #F8F8F2">  </span><span style="color: #66D9EF; font-style: italic">const</span><span style="color: #F8F8F2"> middleValue </span><span style="color: #F92672">=</span><span style="color: #F8F8F2"> array.</span><span style="color: #A6E22E">splice</span><span style="color: #F8F8F2">(middleIndex, </span><span style="color: #AE81FF">1</span><span style="color: #F8F8F2">)[</span><span style="color: #AE81FF">0</span><span style="color: #F8F8F2">]</span></span>
<span class="line"><span style="color: #F8F8F2">  </span><span style="color: #66D9EF; font-style: italic">const</span><span style="color: #F8F8F2"> left</span><span style="color: #F92672">:</span><span style="color: #66D9EF; font-style: italic">number</span><span style="color: #F8F8F2">[] </span><span style="color: #F92672">=</span><span style="color: #F8F8F2"> [], right</span><span style="color: #F92672">:</span><span style="color: #66D9EF; font-style: italic">number</span><span style="color: #F8F8F2">[] </span><span style="color: #F92672">=</span><span style="color: #F8F8F2"> [];</span></span>
<span class="line"><span style="color: #F8F8F2">  </span><span style="color: #F92672">for</span><span style="color: #F8F8F2">(</span><span style="color: #66D9EF; font-style: italic">let</span><span style="color: #F8F8F2"> i </span><span style="color: #F92672">=</span><span style="color: #F8F8F2"> </span><span style="color: #AE81FF">0</span><span style="color: #F8F8F2">; i </span><span style="color: #F92672">&lt;</span><span style="color: #F8F8F2"> array.length; i</span><span style="color: #F92672">++</span><span style="color: #F8F8F2">) {</span></span>
<span class="line"><span style="color: #F8F8F2">    </span><span style="color: #F92672">if</span><span style="color: #F8F8F2">(array[i] </span><span style="color: #F92672">&lt;</span><span style="color: #F8F8F2"> middleValue) {</span></span>
<span class="line"><span style="color: #F8F8F2">      left.</span><span style="color: #A6E22E">push</span><span style="color: #F8F8F2">(array[i])</span></span>
<span class="line"><span style="color: #F8F8F2">    }</span><span style="color: #F92672">else</span><span style="color: #F8F8F2">{</span></span>
<span class="line"><span style="color: #F8F8F2">      right.</span><span style="color: #A6E22E">push</span><span style="color: #F8F8F2">(array[i])</span></span>
<span class="line"><span style="color: #F8F8F2">    }</span></span>
<span class="line"><span style="color: #F8F8F2">  }</span></span>
<span class="line"><span style="color: #F8F8F2">  </span><span style="color: #F92672">return</span><span style="color: #F8F8F2"> </span><span style="color: #A6E22E">quickSpliceSort</span><span style="color: #F8F8F2">(left).</span><span style="color: #A6E22E">concat</span><span style="color: #F8F8F2">([middleValue], </span><span style="color: #A6E22E">quickSpliceSort</span><span style="color: #F8F8F2">(right))</span></span>
<span class="line"><span style="color: #F8F8F2">}</span></span>
<span class="line"></span>
<span class="line"><span style="color: #66D9EF; font-style: italic">const</span><span style="color: #F8F8F2"> arr</span><span style="color: #F92672">:</span><span style="color: #66D9EF; font-style: italic">number</span><span style="color: #F8F8F2"> [] </span><span style="color: #F92672">=</span><span style="color: #F8F8F2"> [</span><span style="color: #AE81FF">1</span><span style="color: #F8F8F2">,</span><span style="color: #AE81FF">4</span><span style="color: #F8F8F2">,</span><span style="color: #AE81FF">3</span><span style="color: #F8F8F2">,</span><span style="color: #AE81FF">5</span><span style="color: #F8F8F2">,</span><span style="color: #AE81FF">7</span><span style="color: #F8F8F2">,</span><span style="color: #AE81FF">2</span><span style="color: #F8F8F2">,</span><span style="color: #AE81FF">6</span><span style="color: #F8F8F2">,</span><span style="color: #AE81FF">9</span><span style="color: #F8F8F2">,</span><span style="color: #AE81FF">8</span><span style="color: #F8F8F2">]</span></span>
<span class="line"><span style="color: #A6E22E">quickSpliceSort</span><span style="color: #F8F8F2">(arr) </span><span style="color: #88846F">// [1, 2, 3, 4, 5, 6, 7, 8, 9]</span></span>
<span class="line"></span>
<span class="line"></span>
<span class="line"><span style="color: #88846F">// ----- 使用slice方法 -------</span></span>
<span class="line"><span style="color: #66D9EF; font-style: italic">function</span><span style="color: #F8F8F2"> </span><span style="color: #A6E22E">quickSliceSort</span><span style="color: #F8F8F2">(</span><span style="color: #FD971F; font-style: italic">array</span><span style="color: #F92672">:</span><span style="color: #F8F8F2"> </span><span style="color: #66D9EF; font-style: italic">number</span><span style="color: #F8F8F2">[])</span><span style="color: #F92672">:</span><span style="color: #66D9EF; font-style: italic">number</span><span style="color: #F8F8F2"> [] {</span></span>
<span class="line"><span style="color: #F8F8F2">  </span><span style="color: #66D9EF; font-style: italic">const</span><span style="color: #F8F8F2"> length </span><span style="color: #F92672">=</span><span style="color: #F8F8F2"> array.length</span></span>
<span class="line"><span style="color: #F8F8F2">  </span><span style="color: #F92672">if</span><span style="color: #F8F8F2">(length </span><span style="color: #F92672">===</span><span style="color: #F8F8F2"> </span><span style="color: #AE81FF">0</span><span style="color: #F8F8F2">) </span><span style="color: #F92672">return</span><span style="color: #F8F8F2"> []</span></span>
<span class="line"><span style="color: #F8F8F2">  </span><span style="color: #66D9EF; font-style: italic">const</span><span style="color: #F8F8F2"> middleIndex </span><span style="color: #F92672">=</span><span style="color: #F8F8F2"> </span><span style="color: #66D9EF">Math</span><span style="color: #F8F8F2">.</span><span style="color: #66D9EF">floor</span><span style="color: #F8F8F2">(length </span><span style="color: #F92672">/</span><span style="color: #F8F8F2"> </span><span style="color: #AE81FF">2</span><span style="color: #F8F8F2">)</span></span>
<span class="line"><span style="color: #F8F8F2">  </span><span style="color: #66D9EF; font-style: italic">const</span><span style="color: #F8F8F2"> middleValue </span><span style="color: #F92672">=</span><span style="color: #F8F8F2"> array.</span><span style="color: #A6E22E">slice</span><span style="color: #F8F8F2">(middleIndex, middleIndex</span><span style="color: #F92672">+</span><span style="color: #AE81FF">1</span><span style="color: #F8F8F2">)[</span><span style="color: #AE81FF">0</span><span style="color: #F8F8F2">]</span></span>
<span class="line"><span style="color: #F8F8F2">  </span><span style="color: #66D9EF; font-style: italic">const</span><span style="color: #F8F8F2"> left</span><span style="color: #F92672">:</span><span style="color: #66D9EF; font-style: italic">number</span><span style="color: #F8F8F2">[] </span><span style="color: #F92672">=</span><span style="color: #F8F8F2"> [], right</span><span style="color: #F92672">:</span><span style="color: #66D9EF; font-style: italic">number</span><span style="color: #F8F8F2">[] </span><span style="color: #F92672">=</span><span style="color: #F8F8F2"> [];</span></span>
<span class="line"><span style="color: #F8F8F2">  </span><span style="color: #F92672">for</span><span style="color: #F8F8F2">(</span><span style="color: #66D9EF; font-style: italic">let</span><span style="color: #F8F8F2"> i </span><span style="color: #F92672">=</span><span style="color: #F8F8F2"> </span><span style="color: #AE81FF">0</span><span style="color: #F8F8F2">; i </span><span style="color: #F92672">&lt;</span><span style="color: #F8F8F2"> length; i</span><span style="color: #F92672">++</span><span style="color: #F8F8F2">) {</span></span>
<span class="line"><span style="color: #F8F8F2">    </span><span style="color: #F92672">if</span><span style="color: #F8F8F2">(i </span><span style="color: #F92672">===</span><span style="color: #F8F8F2"> middleIndex) </span><span style="color: #F92672">continue</span></span>
<span class="line"><span style="color: #F8F8F2">    </span><span style="color: #F92672">if</span><span style="color: #F8F8F2">(array[i] </span><span style="color: #F92672">&lt;</span><span style="color: #F8F8F2"> middleValue) {</span></span>
<span class="line"><span style="color: #F8F8F2">      left.</span><span style="color: #A6E22E">push</span><span style="color: #F8F8F2">(array[i])</span></span>
<span class="line"><span style="color: #F8F8F2">    }</span><span style="color: #F92672">else</span><span style="color: #F8F8F2">{</span></span>
<span class="line"><span style="color: #F8F8F2">      right.</span><span style="color: #A6E22E">push</span><span style="color: #F8F8F2">(array[i])</span></span>
<span class="line"><span style="color: #F8F8F2">    }</span></span>
<span class="line"><span style="color: #F8F8F2">  }</span></span>
<span class="line"><span style="color: #F8F8F2">  </span><span style="color: #F92672">return</span><span style="color: #F8F8F2"> </span><span style="color: #A6E22E">quickSort</span><span style="color: #F8F8F2">(left).</span><span style="color: #A6E22E">concat</span><span style="color: #F8F8F2">([middleValue], </span><span style="color: #A6E22E">quickSort</span><span style="color: #F8F8F2">(right))</span></span>
<span class="line"><span style="color: #F8F8F2">}</span></span>
<span class="line"><span style="color: #66D9EF; font-style: italic">const</span><span style="color: #F8F8F2"> arr</span><span style="color: #F92672">:</span><span style="color: #66D9EF; font-style: italic">number</span><span style="color: #F8F8F2"> [] </span><span style="color: #F92672">=</span><span style="color: #F8F8F2"> [</span><span style="color: #AE81FF">1</span><span style="color: #F8F8F2">,</span><span style="color: #AE81FF">4</span><span style="color: #F8F8F2">,</span><span style="color: #AE81FF">3</span><span style="color: #F8F8F2">,</span><span style="color: #AE81FF">5</span><span style="color: #F8F8F2">,</span><span style="color: #AE81FF">7</span><span style="color: #F8F8F2">,</span><span style="color: #AE81FF">2</span><span style="color: #F8F8F2">,</span><span style="color: #AE81FF">6</span><span style="color: #F8F8F2">,</span><span style="color: #AE81FF">9</span><span style="color: #F8F8F2">,</span><span style="color: #AE81FF">8</span><span style="color: #F8F8F2">]</span></span>
<span class="line"><span style="color: #A6E22E">quickSliceSort</span><span style="color: #F8F8F2">(arr) </span><span style="color: #88846F">// [1, 2, 3, 4, 5, 6, 7, 8, 9]</span></span>
<span class="line"></span></code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></div></template>
