<template><div><h1 id="深拷贝与浅拷贝" tabindex="-1"><a class="header-anchor" href="#深拷贝与浅拷贝" aria-hidden="true">#</a> 深拷贝与浅拷贝</h1>
<h2 id="shallow-copy" tabindex="-1"><a class="header-anchor" href="#shallow-copy" aria-hidden="true">#</a> Shallow Copy</h2>
<p>基本数据类型存储在栈, 而引用数据类型存在堆内存中。变量保存的是对象的内存地址,如果两个变量保存的是同一个对象引用,当其中一个
变量属性修改时,另一个也会受到印象。 而基本数据类型是相互独立的。</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="shiki" style="background-color: #272822"><code><span class="line"><span style="color: #66D9EF; font-style: italic">let</span><span style="color: #F8F8F2"> a </span><span style="color: #F92672">=</span><span style="color: #F8F8F2"> </span><span style="color: #E6DB74">&#39;kyrie&#39;</span></span>
<span class="line"><span style="color: #66D9EF; font-style: italic">let</span><span style="color: #F8F8F2"> b </span><span style="color: #F92672">=</span><span style="color: #F8F8F2"> a;</span></span>
<span class="line"><span style="color: #F8F8F2">console.</span><span style="color: #A6E22E">log</span><span style="color: #F8F8F2">(a,b)  </span><span style="color: #88846F">// kyrie kyrie</span></span>
<span class="line"></span>
<span class="line"><span style="color: #F8F8F2">a </span><span style="color: #F92672">=</span><span style="color: #F8F8F2"> </span><span style="color: #E6DB74">&#39;lebron&#39;</span></span>
<span class="line"><span style="color: #F8F8F2">console.</span><span style="color: #A6E22E">log</span><span style="color: #F8F8F2">(a,b)  </span><span style="color: #88846F">// lebron kyrie</span></span>
<span class="line"><span style="color: #88846F">//-----------------------------------------------------</span></span>
<span class="line"><span style="color: #66D9EF; font-style: italic">const</span><span style="color: #F8F8F2"> player </span><span style="color: #F92672">=</span><span style="color: #F8F8F2"> {</span></span>
<span class="line"><span style="color: #F8F8F2">  firstName:</span><span style="color: #E6DB74">&#39;kyrie&#39;</span><span style="color: #F8F8F2">,</span></span>
<span class="line"><span style="color: #F8F8F2">  lastName: </span><span style="color: #E6DB74">&#39;irving&#39;</span><span style="color: #F8F8F2">,</span></span>
<span class="line"><span style="color: #F8F8F2">  age:</span><span style="color: #AE81FF">29</span></span>
<span class="line"><span style="color: #F8F8F2">}</span></span>
<span class="line"><span style="color: #66D9EF; font-style: italic">let</span><span style="color: #F8F8F2"> p </span><span style="color: #F92672">=</span><span style="color: #F8F8F2"> player;</span></span>
<span class="line"><span style="color: #F8F8F2">p.age </span><span style="color: #F92672">=</span><span style="color: #F8F8F2"> </span><span style="color: #AE81FF">30</span><span style="color: #F8F8F2">;</span></span>
<span class="line"><span style="color: #F8F8F2">console.</span><span style="color: #A6E22E">log</span><span style="color: #F8F8F2">(p,player)</span></span>
<span class="line"><span style="color: #88846F">// {age: 30,firstName: &quot;kyrie&quot;,lastName: &quot;irving&quot;}</span></span>
<span class="line"><span style="color: #88846F">// {age: 30,firstName: &quot;kyrie&quot;,lastName: &quot;irving&quot;}</span></span>
<span class="line"></span></code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>Object.assign()</p>
<p>该方法将所有可枚举属性的值从一个或多个源对象分配到目标对象,它将返回目标对象 (浅拷贝)</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="shiki" style="background-color: #272822"><code><span class="line"><span style="color: #66D9EF; font-style: italic">const</span><span style="color: #F8F8F2"> target </span><span style="color: #F92672">=</span><span style="color: #F8F8F2"> {a:</span><span style="color: #AE81FF">1</span><span style="color: #F8F8F2">,b:{c:</span><span style="color: #AE81FF">0</span><span style="color: #F8F8F2">}}</span></span>
<span class="line"><span style="color: #66D9EF; font-style: italic">let</span><span style="color: #F8F8F2"> obj2 </span><span style="color: #F92672">=</span><span style="color: #F8F8F2"> </span><span style="color: #66D9EF; font-style: italic">Object</span><span style="color: #F8F8F2">.</span><span style="color: #A6E22E">assign</span><span style="color: #F8F8F2">({},target)</span></span>
<span class="line"><span style="color: #F8F8F2">console.</span><span style="color: #A6E22E">log</span><span style="color: #F8F8F2">(obj2) </span><span style="color: #88846F">// {a:1,b:{c:10}}</span></span>
<span class="line"><span style="color: #F8F8F2">target.b.c </span><span style="color: #F92672">=</span><span style="color: #F8F8F2"> </span><span style="color: #AE81FF">10</span><span style="color: #F8F8F2">;</span></span>
<span class="line"><span style="color: #F8F8F2">console.</span><span style="color: #A6E22E">log</span><span style="color: #F8F8F2">(obj2) </span><span style="color: #88846F">// {a:1,b:{c:10}}</span></span>
<span class="line"></span>
<span class="line"><span style="color: #F8F8F2">target.a </span><span style="color: #F92672">=</span><span style="color: #F8F8F2"> </span><span style="color: #AE81FF">10</span><span style="color: #F8F8F2">;</span></span>
<span class="line"><span style="color: #F8F8F2">console.</span><span style="color: #A6E22E">log</span><span style="color: #F8F8F2">(target,obj2)</span></span>
<span class="line"><span style="color: #88846F">// {a:10,b:{c:10}}</span></span>
<span class="line"><span style="color: #88846F">// {a:1,b:{c:10}}</span></span>
<span class="line"></span></code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><a href="https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Object/assign" target="_blank" rel="noopener noreferrer">MDN-Object.assign文档<ExternalLinkIcon/></a></p>
<p><a href="https://es6.ruanyifeng.com/#docs/object-methods#Object-assign" target="_blank" rel="noopener noreferrer">对象新增的方法<ExternalLinkIcon/></a></p>
<p>对象的扩展运算符 (浅拷贝)</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="shiki" style="background-color: #272822"><code><span class="line"><span style="color: #66D9EF; font-style: italic">let</span><span style="color: #F8F8F2"> a </span><span style="color: #F92672">=</span><span style="color: #F8F8F2"> {name:</span><span style="color: #E6DB74">&#39;You do not known javascript&#39;</span><span style="color: #F8F8F2">,info:{price:</span><span style="color: #AE81FF">40</span><span style="color: #F8F8F2">}}</span></span>
<span class="line"><span style="color: #66D9EF; font-style: italic">let</span><span style="color: #F8F8F2"> b </span><span style="color: #F92672">=</span><span style="color: #F8F8F2"> {</span><span style="color: #F92672">...</span><span style="color: #F8F8F2">a}</span></span>
<span class="line"><span style="color: #F8F8F2">a.info.price </span><span style="color: #F92672">=</span><span style="color: #F8F8F2"> </span><span style="color: #AE81FF">50</span></span>
<span class="line"><span style="color: #F8F8F2">console.</span><span style="color: #A6E22E">log</span><span style="color: #F8F8F2">(a,b)</span></span>
<span class="line"><span style="color: #88846F">// {info: {price: 50}, name: &quot;You do not known javascript&quot;}</span></span>
<span class="line"></span></code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>Array.prototype.slice()
该方法返回一个新的数组对象, 这个对象是一个由begin和end决定的原数组的浅拷贝,原数组不会被改变</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="shiki" style="background-color: #272822"><code><span class="line"><span style="color: #66D9EF; font-style: italic">const</span><span style="color: #F8F8F2"> player_list </span><span style="color: #F92672">=</span><span style="color: #F8F8F2"> [{name:</span><span style="color: #E6DB74">&#39;kyrie&#39;</span><span style="color: #F8F8F2">},{name:</span><span style="color: #E6DB74">&#39;lebron&#39;</span><span style="color: #F8F8F2">},{name:</span><span style="color: #E6DB74">&#39;durant&#39;</span><span style="color: #F8F8F2">}];</span></span>
<span class="line"><span style="color: #66D9EF; font-style: italic">const</span><span style="color: #F8F8F2"> copy_player_list </span><span style="color: #F92672">=</span><span style="color: #F8F8F2"> player_list.</span><span style="color: #A6E22E">slice</span><span style="color: #F8F8F2">()</span></span>
<span class="line"></span>
<span class="line"><span style="color: #F8F8F2">copy_player_list[</span><span style="color: #AE81FF">0</span><span style="color: #F8F8F2">][</span><span style="color: #E6DB74">&#39;name&#39;</span><span style="color: #F8F8F2">] </span><span style="color: #F92672">=</span><span style="color: #F8F8F2"> </span><span style="color: #E6DB74">&#39;wade&#39;</span><span style="color: #F8F8F2">;</span></span>
<span class="line"></span>
<span class="line"><span style="color: #F8F8F2">console.</span><span style="color: #A6E22E">log</span><span style="color: #F8F8F2">(player_list, copy_player_list)</span></span>
<span class="line"><span style="color: #88846F">// [{name:&#39;wade&#39;},{name:&#39;lebron&#39;},{name:&#39;durant&#39;}]</span></span>
<span class="line"><span style="color: #88846F">// [{name:&#39;wade&#39;},{name:&#39;lebron&#39;},{name:&#39;durant&#39;}]</span></span>
<span class="line"></span></code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><a href="https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Array/slice" target="_blank" rel="noopener noreferrer">MDN-Array.prototype.slice<ExternalLinkIcon/></a></p>
<p><a href="https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Array/concat" target="_blank" rel="noopener noreferrer">MDN-Array.prototype.concat<ExternalLinkIcon/></a></p>
<h2 id="deep-copy" tabindex="-1"><a class="header-anchor" href="#deep-copy" aria-hidden="true">#</a> Deep Copy</h2>
<ol>
<li>JSON.stringify()</li>
</ol>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="shiki" style="background-color: #272822"><code><span class="line"><span style="color: #66D9EF; font-style: italic">let</span><span style="color: #F8F8F2"> book </span><span style="color: #F92672">=</span><span style="color: #F8F8F2"> {</span></span>
<span class="line"><span style="color: #F8F8F2">  name: </span><span style="color: #E6DB74">&#39;JavaScript高级程序设计&#39;</span><span style="color: #F8F8F2">,</span></span>
<span class="line"><span style="color: #F8F8F2">  info:{</span></span>
<span class="line"><span style="color: #F8F8F2">    price:</span><span style="color: #AE81FF">100</span></span>
<span class="line"><span style="color: #F8F8F2">  }</span></span>
<span class="line"><span style="color: #F8F8F2">}</span></span>
<span class="line"><span style="color: #66D9EF; font-style: italic">let</span><span style="color: #F8F8F2"> copy_book </span><span style="color: #F92672">=</span><span style="color: #F8F8F2"> </span><span style="color: #66D9EF">JSON</span><span style="color: #F8F8F2">.</span><span style="color: #66D9EF">parse</span><span style="color: #F8F8F2">(</span><span style="color: #66D9EF">JSON</span><span style="color: #F8F8F2">.</span><span style="color: #66D9EF">stringify</span><span style="color: #F8F8F2">(book))</span></span>
<span class="line"><span style="color: #F8F8F2">copy_book.info.price </span><span style="color: #F92672">=</span><span style="color: #F8F8F2"> </span><span style="color: #AE81FF">101</span><span style="color: #F8F8F2">;</span></span>
<span class="line"><span style="color: #F8F8F2">console.</span><span style="color: #A6E22E">log</span><span style="color: #F8F8F2">(book,copy_book)</span></span>
<span class="line"><span style="color: #88846F">/*</span></span>
<span class="line"><span style="color: #88846F">let book = {</span></span>
<span class="line"><span style="color: #88846F">  name: &#39;JavaScript高级程序设计&#39;,</span></span>
<span class="line"><span style="color: #88846F">  info:{</span></span>
<span class="line"><span style="color: #88846F">    price:100</span></span>
<span class="line"><span style="color: #88846F">  }</span></span>
<span class="line"><span style="color: #88846F">}</span></span>
<span class="line"></span>
<span class="line"><span style="color: #88846F">let book = {</span></span>
<span class="line"><span style="color: #88846F">  name: &#39;JavaScript高级程序设计&#39;,</span></span>
<span class="line"><span style="color: #88846F">  info:{</span></span>
<span class="line"><span style="color: #88846F">    price:101</span></span>
<span class="line"><span style="color: #88846F">  }</span></span>
<span class="line"><span style="color: #88846F">}</span></span>
<span class="line"><span style="color: #88846F">*/</span></span>
<span class="line"></span></code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>使用JSON.stringify()方法有一些问题:</p>
<ol>
<li>undefined symbol及 任意的函数值 在序列化过程中会被忽略</li>
<li>所有以symbol为属性键的属性都会被完全忽略</li>
<li>对包含循环引用的对象(对象之间相互引用,形成无限循环)执行此方法,会抛出错误</li>
</ol>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="shiki" style="background-color: #272822"><code><span class="line"><span style="color: #66D9EF; font-style: italic">const</span><span style="color: #F8F8F2"> obj1 </span><span style="color: #F92672">=</span><span style="color: #F8F8F2"> {</span></span>
<span class="line"><span style="color: #F8F8F2">  name:</span><span style="color: #E6DB74">&#39;kyrie&#39;</span><span style="color: #F8F8F2">,</span></span>
<span class="line"><span style="color: #F8F8F2">  a:</span><span style="color: #AE81FF">undefined</span><span style="color: #F8F8F2">,</span></span>
<span class="line"><span style="color: #F8F8F2">  b:</span><span style="color: #66D9EF; font-style: italic">Symbol</span><span style="color: #F8F8F2">(</span><span style="color: #E6DB74">&#39;foo&#39;</span><span style="color: #F8F8F2">),</span></span>
<span class="line"><span style="color: #F8F8F2">  </span><span style="color: #A6E22E">c</span><span style="color: #F8F8F2">:</span><span style="color: #66D9EF; font-style: italic">function</span><span style="color: #F8F8F2"> </span><span style="color: #A6E22E">f</span><span style="color: #F8F8F2"> (){}</span></span>
<span class="line"><span style="color: #F8F8F2">}</span></span>
<span class="line"><span style="color: #F8F8F2">console.</span><span style="color: #A6E22E">log</span><span style="color: #F8F8F2">(</span><span style="color: #66D9EF">JSON</span><span style="color: #F8F8F2">.</span><span style="color: #66D9EF">stringify</span><span style="color: #F8F8F2">(obj1)) </span><span style="color: #88846F">// {&quot;name&quot;:&quot;kyrie&quot;}</span></span>
<span class="line"></span></code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>实现一个深拷贝</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="shiki" style="background-color: #272822"><code><span class="line"><span style="color: #66D9EF; font-style: italic">function</span><span style="color: #F8F8F2"> </span><span style="color: #A6E22E">deepClone</span><span style="color: #F8F8F2">(</span><span style="color: #FD971F; font-style: italic">source</span><span style="color: #F8F8F2">) {</span></span>
<span class="line"><span style="color: #F8F8F2">  </span><span style="color: #88846F">// typeof []/typeof {} / typeof null 都返回 object</span></span>
<span class="line"><span style="color: #F8F8F2">  </span><span style="color: #F92672">if</span><span style="color: #F8F8F2">(</span><span style="color: #F92672">typeof</span><span style="color: #F8F8F2"> source </span><span style="color: #F92672">===</span><span style="color: #F8F8F2"> </span><span style="color: #E6DB74">&#39;object&#39;</span><span style="color: #F8F8F2"> </span><span style="color: #F92672">&amp;&amp;</span><span style="color: #F8F8F2"> source </span><span style="color: #F92672">!==</span><span style="color: #F8F8F2"> </span><span style="color: #AE81FF">null</span><span style="color: #F8F8F2">) {</span></span>
<span class="line"><span style="color: #F8F8F2">    </span><span style="color: #66D9EF; font-style: italic">let</span><span style="color: #F8F8F2"> target </span><span style="color: #F92672">=</span><span style="color: #F8F8F2"> </span><span style="color: #66D9EF; font-style: italic">Array</span><span style="color: #F8F8F2">.</span><span style="color: #A6E22E">isArray</span><span style="color: #F8F8F2">(source) </span><span style="color: #F92672">?</span><span style="color: #F8F8F2"> [] </span><span style="color: #F92672">:</span><span style="color: #F8F8F2"> {};</span></span>
<span class="line"><span style="color: #F8F8F2">    </span><span style="color: #F92672">for</span><span style="color: #F8F8F2">(</span><span style="color: #66D9EF; font-style: italic">let</span><span style="color: #F8F8F2"> key </span><span style="color: #F92672">of</span><span style="color: #F8F8F2"> </span><span style="color: #66D9EF; font-style: italic">Object</span><span style="color: #F8F8F2">.</span><span style="color: #A6E22E">keys</span><span style="color: #F8F8F2">(source)) {</span></span>
<span class="line"><span style="color: #F8F8F2">      </span><span style="color: #F92672">if</span><span style="color: #F8F8F2">(</span><span style="color: #F92672">typeof</span><span style="color: #F8F8F2"> source[key] </span><span style="color: #F92672">===</span><span style="color: #F8F8F2"> </span><span style="color: #E6DB74">&#39;object&#39;</span><span style="color: #F8F8F2">) {</span></span>
<span class="line"><span style="color: #F8F8F2">        target[key] </span><span style="color: #F92672">=</span><span style="color: #F8F8F2"> </span><span style="color: #A6E22E">deepClone</span><span style="color: #F8F8F2">(source[key])</span></span>
<span class="line"><span style="color: #F8F8F2">      }</span><span style="color: #F92672">else</span><span style="color: #F8F8F2">{</span></span>
<span class="line"><span style="color: #F8F8F2">        target[key] </span><span style="color: #F92672">=</span><span style="color: #F8F8F2"> source[key]</span></span>
<span class="line"><span style="color: #F8F8F2">      }</span></span>
<span class="line"><span style="color: #F8F8F2">    }</span></span>
<span class="line"><span style="color: #F8F8F2">    </span><span style="color: #F92672">return</span><span style="color: #F8F8F2"> target;</span></span>
<span class="line"><span style="color: #F8F8F2">  }</span><span style="color: #F92672">else</span><span style="color: #F8F8F2">{</span></span>
<span class="line"><span style="color: #F8F8F2">    </span><span style="color: #F92672">return</span><span style="color: #F8F8F2"> source</span></span>
<span class="line"><span style="color: #F8F8F2">  }</span></span>
<span class="line"><span style="color: #F8F8F2">}</span></span>
<span class="line"><span style="color: #66D9EF; font-style: italic">let</span><span style="color: #F8F8F2"> copy_book </span><span style="color: #F92672">=</span><span style="color: #F8F8F2"> </span><span style="color: #A6E22E">deepClone</span><span style="color: #F8F8F2">(book)</span></span>
<span class="line"><span style="color: #F8F8F2">copy_book.info.price </span><span style="color: #F92672">=</span><span style="color: #F8F8F2"> </span><span style="color: #AE81FF">101</span><span style="color: #F8F8F2">;</span></span>
<span class="line"><span style="color: #F8F8F2">console.</span><span style="color: #A6E22E">log</span><span style="color: #F8F8F2">(book,copy_book)</span></span>
<span class="line"><span style="color: #88846F">/*</span></span>
<span class="line"><span style="color: #88846F">* let book = {</span></span>
<span class="line"><span style="color: #88846F">  name: &#39;JavaScript高级程序设计&#39;,</span></span>
<span class="line"><span style="color: #88846F">  info:{</span></span>
<span class="line"><span style="color: #88846F">    price:100</span></span>
<span class="line"><span style="color: #88846F">  }</span></span>
<span class="line"><span style="color: #88846F">}</span></span>
<span class="line"></span>
<span class="line"><span style="color: #88846F">let book = {</span></span>
<span class="line"><span style="color: #88846F">  name: &#39;JavaScript高级程序设计&#39;,</span></span>
<span class="line"><span style="color: #88846F">  info:{</span></span>
<span class="line"><span style="color: #88846F">    price:101</span></span>
<span class="line"><span style="color: #88846F">  }</span></span>
<span class="line"><span style="color: #88846F">}</span></span>
<span class="line"><span style="color: #88846F">* */</span></span>
<span class="line"></span>
<span class="line"><span style="color: #66D9EF; font-style: italic">const</span><span style="color: #F8F8F2"> players </span><span style="color: #F92672">=</span><span style="color: #F8F8F2"> [</span></span>
<span class="line"><span style="color: #F8F8F2">  {</span></span>
<span class="line"><span style="color: #F8F8F2">    firstName: </span><span style="color: #E6DB74">&#39;kyrie&#39;</span><span style="color: #F8F8F2">,</span></span>
<span class="line"><span style="color: #F8F8F2">    lastName: </span><span style="color: #E6DB74">&#39;irving&#39;</span></span>
<span class="line"><span style="color: #F8F8F2">  },</span></span>
<span class="line"><span style="color: #F8F8F2">  {</span></span>
<span class="line"><span style="color: #F8F8F2">    firstName: </span><span style="color: #E6DB74">&#39;lebron&#39;</span><span style="color: #F8F8F2">,</span></span>
<span class="line"><span style="color: #F8F8F2">    lastName: </span><span style="color: #E6DB74">&#39;james&#39;</span></span>
<span class="line"><span style="color: #F8F8F2">  }</span></span>
<span class="line"><span style="color: #F8F8F2">]</span></span>
<span class="line"><span style="color: #66D9EF; font-style: italic">const</span><span style="color: #F8F8F2"> clone_players </span><span style="color: #F92672">=</span><span style="color: #F8F8F2"> </span><span style="color: #A6E22E">deepClone</span><span style="color: #F8F8F2">(players)</span></span>
<span class="line"><span style="color: #F8F8F2">players[</span><span style="color: #AE81FF">0</span><span style="color: #F8F8F2">][</span><span style="color: #E6DB74">&#39;age&#39;</span><span style="color: #F8F8F2">] </span><span style="color: #F92672">=</span><span style="color: #F8F8F2"> </span><span style="color: #AE81FF">100</span></span>
<span class="line"><span style="color: #F8F8F2">console.</span><span style="color: #A6E22E">log</span><span style="color: #F8F8F2">(clone_players)</span></span>
<span class="line"><span style="color: #88846F">/*</span></span>
<span class="line"><span style="color: #88846F">{</span></span>
<span class="line"><span style="color: #88846F">  &#39;0&#39;: { firstName: &#39;kyrie&#39;, lastName: &#39;irving&#39; },</span></span>
<span class="line"><span style="color: #88846F">  &#39;1&#39;: { firstName: &#39;lebron&#39;, lastName: &#39;james&#39; }</span></span>
<span class="line"><span style="color: #88846F">}</span></span>
<span class="line"><span style="color: #88846F">*/</span></span>
<span class="line"><span style="color: #F8F8F2">console.</span><span style="color: #A6E22E">log</span><span style="color: #F8F8F2">(players)</span></span>
<span class="line"><span style="color: #88846F">/*</span></span>
<span class="line"><span style="color: #88846F">[</span></span>
<span class="line"><span style="color: #88846F">  { firstName: &#39;kyrie&#39;, lastName: &#39;irving&#39;, age: 100 },</span></span>
<span class="line"><span style="color: #88846F">  { firstName: &#39;lebron&#39;, lastName: &#39;james&#39; }</span></span>
<span class="line"><span style="color: #88846F">]</span></span>
<span class="line"><span style="color: #88846F">*/</span></span>
<span class="line"></span></code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>但是上面的算法不支持Map/Set结构,也无法解决循环引用问题。</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="shiki" style="background-color: #272822"><code><span class="line"><span style="color: #88846F">// ----- map 结构 -------</span></span>
<span class="line"><span style="color: #66D9EF; font-style: italic">const</span><span style="color: #F8F8F2"> map </span><span style="color: #F92672">=</span><span style="color: #F8F8F2"> </span><span style="color: #F92672">new</span><span style="color: #F8F8F2"> </span><span style="color: #66D9EF; font-style: italic">Map</span><span style="color: #F8F8F2">([</span></span>
<span class="line"><span style="color: #F8F8F2">  [</span><span style="color: #E6DB74">&#39;name&#39;</span><span style="color: #F8F8F2">, </span><span style="color: #E6DB74">&#39;张三&#39;</span><span style="color: #F8F8F2">],</span></span>
<span class="line"><span style="color: #F8F8F2">  [</span><span style="color: #E6DB74">&#39;title&#39;</span><span style="color: #F8F8F2">, </span><span style="color: #E6DB74">&#39;Author&#39;</span><span style="color: #F8F8F2">]</span></span>
<span class="line"><span style="color: #F8F8F2">])</span></span>
<span class="line"></span>
<span class="line"><span style="color: #66D9EF; font-style: italic">const</span><span style="color: #F8F8F2"> clone_map </span><span style="color: #F92672">=</span><span style="color: #F8F8F2"> </span><span style="color: #A6E22E">deepClone</span><span style="color: #F8F8F2">(map)</span></span>
<span class="line"><span style="color: #F8F8F2">console.</span><span style="color: #A6E22E">log</span><span style="color: #F8F8F2">(clone_map)  </span><span style="color: #88846F">// {}</span></span>
<span class="line"></span>
<span class="line"><span style="color: #88846F">// ------ set结构 -------</span></span>
<span class="line"><span style="color: #66D9EF; font-style: italic">const</span><span style="color: #F8F8F2"> s1 </span><span style="color: #F92672">=</span><span style="color: #F8F8F2"> </span><span style="color: #F92672">new</span><span style="color: #F8F8F2"> </span><span style="color: #66D9EF; font-style: italic">Set</span><span style="color: #F8F8F2">()</span></span>
<span class="line"><span style="color: #66D9EF; font-style: italic">const</span><span style="color: #F8F8F2"> s2 </span><span style="color: #F92672">=</span><span style="color: #F8F8F2"> </span><span style="color: #F92672">new</span><span style="color: #F8F8F2"> </span><span style="color: #66D9EF; font-style: italic">Set</span><span style="color: #F8F8F2">()</span></span>
<span class="line"><span style="color: #F8F8F2">s1.</span><span style="color: #A6E22E">add</span><span style="color: #F8F8F2">(</span><span style="color: #E6DB74">&#39;hello&#39;</span><span style="color: #F8F8F2">)</span></span>
<span class="line"><span style="color: #F8F8F2">s2.</span><span style="color: #A6E22E">add</span><span style="color: #F8F8F2">(</span><span style="color: #E6DB74">&#39;world&#39;</span><span style="color: #F8F8F2">)</span></span>
<span class="line"><span style="color: #F8F8F2">console.</span><span style="color: #A6E22E">log</span><span style="color: #F8F8F2">([s1, s2]) </span><span style="color: #88846F">// [ Set(1) { &#39;hello&#39; }, Set(1) { &#39;world&#39; } ]</span></span>
<span class="line"><span style="color: #F8F8F2">console.</span><span style="color: #A6E22E">log</span><span style="color: #F8F8F2">(</span><span style="color: #A6E22E">clone</span><span style="color: #F8F8F2">([s1, s2]))  </span><span style="color: #88846F">// [ {}, {} ]</span></span>
<span class="line"></span></code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="深拷贝-map-set-array-object" tabindex="-1"><a class="header-anchor" href="#深拷贝-map-set-array-object" aria-hidden="true">#</a> 深拷贝(Map/Set/Array/Object)</h2>
<div class="language-typescript ext-ts line-numbers-mode"><pre v-pre class="shiki" style="background-color: #272822"><code><span class="line"><span style="color: #88846F">// ------------ 支持array/object/map/set -------------</span></span>
<span class="line"><span style="color: #66D9EF; font-style: italic">function</span><span style="color: #F8F8F2"> </span><span style="color: #A6E22E">deep_clone</span><span style="color: #F8F8F2">(</span><span style="color: #FD971F; font-style: italic">object</span><span style="color: #F92672">:</span><span style="color: #F8F8F2"> </span><span style="color: #66D9EF; font-style: italic">any</span><span style="color: #F8F8F2">, </span><span style="color: #FD971F; font-style: italic">map</span><span style="color: #F8F8F2"> </span><span style="color: #F92672">=</span><span style="color: #F8F8F2"> </span><span style="color: #F92672">new</span><span style="color: #F8F8F2"> </span><span style="color: #66D9EF; font-style: italic">WeakMap</span><span style="color: #F8F8F2">()) </span><span style="color: #F92672">:</span><span style="color: #66D9EF; font-style: italic">any</span><span style="color: #F8F8F2"> {</span></span>
<span class="line"><span style="color: #F8F8F2">  </span><span style="color: #F92672">if</span><span style="color: #F8F8F2">(</span><span style="color: #F92672">typeof</span><span style="color: #F8F8F2"> object </span><span style="color: #F92672">!==</span><span style="color: #F8F8F2"> </span><span style="color: #E6DB74">&#39;object&#39;</span><span style="color: #F8F8F2"> </span><span style="color: #F92672">||</span><span style="color: #F8F8F2"> object </span><span style="color: #F92672">==</span><span style="color: #F8F8F2"> </span><span style="color: #AE81FF">null</span><span style="color: #F8F8F2">) </span><span style="color: #F92672">return</span><span style="color: #F8F8F2"> object</span></span>
<span class="line"><span style="color: #F8F8F2">  </span><span style="color: #66D9EF; font-style: italic">const</span><span style="color: #F8F8F2"> fromMap </span><span style="color: #F92672">=</span><span style="color: #F8F8F2"> map.</span><span style="color: #A6E22E">get</span><span style="color: #F8F8F2">(object) </span><span style="color: #88846F">// 判断是否循环引用了</span></span>
<span class="line"><span style="color: #F8F8F2">  </span><span style="color: #F92672">if</span><span style="color: #F8F8F2">(fromMap) </span><span style="color: #F92672">return</span><span style="color: #F8F8F2"> fromMap</span></span>
<span class="line"><span style="color: #F8F8F2">  </span><span style="color: #66D9EF; font-style: italic">let</span><span style="color: #F8F8F2"> target</span><span style="color: #F92672">:</span><span style="color: #F8F8F2"> </span><span style="color: #66D9EF; font-style: italic">any</span><span style="color: #F8F8F2"> </span><span style="color: #F92672">=</span><span style="color: #F8F8F2"> {};</span></span>
<span class="line"><span style="color: #F8F8F2">  map.</span><span style="color: #A6E22E">set</span><span style="color: #F8F8F2">(object, target)</span></span>
<span class="line"><span style="color: #F8F8F2">  </span><span style="color: #66D9EF; font-style: italic">const</span><span style="color: #F8F8F2"> type </span><span style="color: #F92672">=</span><span style="color: #F8F8F2"> </span><span style="color: #66D9EF; font-style: italic">Object</span><span style="color: #F8F8F2">.prototype.toString.</span><span style="color: #A6E22E">call</span><span style="color: #F8F8F2">(object).</span><span style="color: #A6E22E">slice</span><span style="color: #F8F8F2">(</span><span style="color: #AE81FF">8</span><span style="color: #F8F8F2">,</span><span style="color: #F92672">-</span><span style="color: #AE81FF">1</span><span style="color: #F8F8F2">)</span></span>
<span class="line"><span style="color: #F8F8F2">  </span><span style="color: #F92672">switch</span><span style="color: #F8F8F2">(type) {</span></span>
<span class="line"><span style="color: #F8F8F2">    </span><span style="color: #F92672">case</span><span style="color: #F8F8F2"> </span><span style="color: #E6DB74">&#39;Map&#39;</span><span style="color: #F8F8F2">: {</span></span>
<span class="line"><span style="color: #F8F8F2">      target </span><span style="color: #F92672">=</span><span style="color: #F8F8F2"> </span><span style="color: #F92672">new</span><span style="color: #F8F8F2"> </span><span style="color: #66D9EF; font-style: italic">Map</span><span style="color: #F8F8F2">()</span></span>
<span class="line"><span style="color: #F8F8F2">      object.</span><span style="color: #A6E22E">forEach</span><span style="color: #F8F8F2">((</span><span style="color: #FD971F; font-style: italic">value</span><span style="color: #F8F8F2">, </span><span style="color: #FD971F; font-style: italic">key</span><span style="color: #F8F8F2">) </span><span style="color: #66D9EF; font-style: italic">=&gt;</span><span style="color: #F8F8F2"> {</span></span>
<span class="line"><span style="color: #F8F8F2">        target.</span><span style="color: #A6E22E">set</span><span style="color: #F8F8F2">(</span><span style="color: #A6E22E">deep_clone</span><span style="color: #F8F8F2">(value, map), </span><span style="color: #A6E22E">deep_clone</span><span style="color: #F8F8F2">(key, map))</span></span>
<span class="line"><span style="color: #F8F8F2">      })</span></span>
<span class="line"><span style="color: #F8F8F2">    }</span></span>
<span class="line"><span style="color: #F8F8F2">    </span><span style="color: #F92672">break</span><span style="color: #F8F8F2">;</span></span>
<span class="line"><span style="color: #F8F8F2">    </span><span style="color: #F92672">case</span><span style="color: #F8F8F2"> </span><span style="color: #E6DB74">&#39;Set&#39;</span><span style="color: #F8F8F2">: {</span></span>
<span class="line"><span style="color: #F8F8F2">      target </span><span style="color: #F92672">=</span><span style="color: #F8F8F2"> </span><span style="color: #F92672">new</span><span style="color: #F8F8F2"> </span><span style="color: #66D9EF; font-style: italic">Set</span><span style="color: #F8F8F2">()</span></span>
<span class="line"><span style="color: #F8F8F2">      object.</span><span style="color: #A6E22E">forEach</span><span style="color: #F8F8F2">(</span><span style="color: #FD971F; font-style: italic">v</span><span style="color: #F8F8F2"> </span><span style="color: #66D9EF; font-style: italic">=&gt;</span><span style="color: #F8F8F2"> {</span></span>
<span class="line"><span style="color: #F8F8F2">        target.</span><span style="color: #A6E22E">add</span><span style="color: #F8F8F2">(</span><span style="color: #A6E22E">deep_clone</span><span style="color: #F8F8F2">(v), map)</span></span>
<span class="line"><span style="color: #F8F8F2">      })</span></span>
<span class="line"><span style="color: #F8F8F2">    }</span></span>
<span class="line"><span style="color: #F8F8F2">    </span><span style="color: #F92672">break</span><span style="color: #F8F8F2">;</span></span>
<span class="line"><span style="color: #F8F8F2">    </span><span style="color: #F92672">case</span><span style="color: #F8F8F2"> </span><span style="color: #E6DB74">&#39;Array&#39;</span><span style="color: #F8F8F2">: {</span></span>
<span class="line"><span style="color: #F8F8F2">      target </span><span style="color: #F92672">=</span><span style="color: #F8F8F2"> object.</span><span style="color: #A6E22E">map</span><span style="color: #F8F8F2">(</span><span style="color: #FD971F; font-style: italic">item</span><span style="color: #F8F8F2"> </span><span style="color: #66D9EF; font-style: italic">=&gt;</span><span style="color: #F8F8F2"> </span><span style="color: #A6E22E">deep_clone</span><span style="color: #F8F8F2">(item), map)</span></span>
<span class="line"><span style="color: #F8F8F2">    }</span></span>
<span class="line"><span style="color: #F8F8F2">    </span><span style="color: #F92672">break</span><span style="color: #F8F8F2">;</span></span>
<span class="line"><span style="color: #F8F8F2">    </span><span style="color: #F92672">case</span><span style="color: #F8F8F2"> </span><span style="color: #E6DB74">&#39;Object&#39;</span><span style="color: #F8F8F2">: {</span></span>
<span class="line"><span style="color: #F8F8F2">      target </span><span style="color: #F92672">=</span><span style="color: #F8F8F2"> {}</span></span>
<span class="line"><span style="color: #F8F8F2">      </span><span style="color: #F92672">for</span><span style="color: #F8F8F2">(</span><span style="color: #66D9EF; font-style: italic">const</span><span style="color: #F8F8F2"> key </span><span style="color: #F92672">in</span><span style="color: #F8F8F2"> object) {</span></span>
<span class="line"><span style="color: #F8F8F2">        </span><span style="color: #66D9EF; font-style: italic">const</span><span style="color: #F8F8F2"> v </span><span style="color: #F92672">=</span><span style="color: #F8F8F2"> </span><span style="color: #A6E22E">deep_clone</span><span style="color: #F8F8F2">(object[key], map)</span></span>
<span class="line"><span style="color: #F8F8F2">        target[key] </span><span style="color: #F92672">=</span><span style="color: #F8F8F2"> v</span></span>
<span class="line"><span style="color: #F8F8F2">      }</span></span>
<span class="line"><span style="color: #F8F8F2">    }</span></span>
<span class="line"><span style="color: #F8F8F2">    </span><span style="color: #F92672">break</span><span style="color: #F8F8F2">;</span></span>
<span class="line"><span style="color: #F8F8F2">  }</span></span>
<span class="line"><span style="color: #F8F8F2">  </span><span style="color: #F92672">return</span><span style="color: #F8F8F2"> target</span></span>
<span class="line"><span style="color: #F8F8F2">}</span></span>
<span class="line"></span>
<span class="line"><span style="color: #88846F">// ----- 测试 ------</span></span>
<span class="line"><span style="color: #66D9EF; font-style: italic">const</span><span style="color: #F8F8F2"> k1 </span><span style="color: #F92672">=</span><span style="color: #F8F8F2"> [</span><span style="color: #F92672">new</span><span style="color: #F8F8F2"> </span><span style="color: #66D9EF; font-style: italic">Set</span><span style="color: #F8F8F2">().</span><span style="color: #A6E22E">add</span><span style="color: #F8F8F2">(</span><span style="color: #E6DB74">&#39;hello&#39;</span><span style="color: #F8F8F2">), </span><span style="color: #F92672">new</span><span style="color: #F8F8F2"> </span><span style="color: #66D9EF; font-style: italic">Set</span><span style="color: #F8F8F2">().</span><span style="color: #A6E22E">add</span><span style="color: #F8F8F2">(</span><span style="color: #E6DB74">&#39;world&#39;</span><span style="color: #F8F8F2">)]</span></span>
<span class="line"><span style="color: #F8F8F2">console.</span><span style="color: #A6E22E">log</span><span style="color: #F8F8F2">(</span><span style="color: #E6DB74">&#39;k1:&#39;</span><span style="color: #F8F8F2">, </span><span style="color: #A6E22E">deep_clone</span><span style="color: #F8F8F2">(k1))  </span><span style="color: #88846F">// [ Set(1) { &#39;hello&#39; }, Set(1) { &#39;world&#39; } ]</span></span>
<span class="line"></span>
<span class="line"><span style="color: #66D9EF; font-style: italic">const</span><span style="color: #F8F8F2"> k2 </span><span style="color: #F92672">=</span><span style="color: #F8F8F2"> [</span><span style="color: #F92672">new</span><span style="color: #F8F8F2"> </span><span style="color: #66D9EF; font-style: italic">Map</span><span style="color: #F8F8F2">([[</span><span style="color: #E6DB74">&#39;hello&#39;</span><span style="color: #F8F8F2">, </span><span style="color: #E6DB74">&#39;world&#39;</span><span style="color: #F8F8F2">], [</span><span style="color: #E6DB74">&#39;你好&#39;</span><span style="color: #F8F8F2">, </span><span style="color: #E6DB74">&#39;生活&#39;</span><span style="color: #F8F8F2">]])]</span></span>
<span class="line"><span style="color: #F8F8F2">console.</span><span style="color: #A6E22E">log</span><span style="color: #F8F8F2">(</span><span style="color: #E6DB74">&#39;k2&#39;</span><span style="color: #F8F8F2">, </span><span style="color: #A6E22E">deep_clone</span><span style="color: #F8F8F2">(k2)) </span><span style="color: #88846F">// [ Map(2) { &#39;world&#39; =&gt; &#39;hello&#39;, &#39;生活&#39; =&gt; &#39;你好&#39; } ]</span></span>
<span class="line"></span>
<span class="line"><span style="color: #66D9EF; font-style: italic">const</span><span style="color: #F8F8F2"> k3 </span><span style="color: #F92672">=</span><span style="color: #F8F8F2"> {</span></span>
<span class="line"><span style="color: #F8F8F2">  name: </span><span style="color: #E6DB74">&#39;hello&#39;</span><span style="color: #F8F8F2">,</span></span>
<span class="line"><span style="color: #F8F8F2">}</span></span>
<span class="line"><span style="color: #66D9EF; font-style: italic">const</span><span style="color: #F8F8F2"> deep_k3 </span><span style="color: #F92672">=</span><span style="color: #F8F8F2"> </span><span style="color: #A6E22E">deep_clone</span><span style="color: #F8F8F2">(k3)</span></span>
<span class="line"><span style="color: #F8F8F2">k3.name </span><span style="color: #F92672">=</span><span style="color: #F8F8F2"> </span><span style="color: #E6DB74">&#39;你好&#39;</span></span>
<span class="line"><span style="color: #F8F8F2">console.</span><span style="color: #A6E22E">log</span><span style="color: #F8F8F2">(deep_k3)  </span><span style="color: #88846F">// { name: &#39;hello&#39; }</span></span>
<span class="line"></span>
<span class="line"></span>
<span class="line"><span style="color: #66D9EF; font-style: italic">const</span><span style="color: #F8F8F2"> o </span><span style="color: #F92672">=</span><span style="color: #F8F8F2"> {</span></span>
<span class="line"><span style="color: #F8F8F2">  a: </span><span style="color: #AE81FF">null</span></span>
<span class="line"><span style="color: #F8F8F2">}</span></span>
<span class="line"><span style="color: #F8F8F2">o.a </span><span style="color: #F92672">=</span><span style="color: #F8F8F2"> o</span></span>
<span class="line"></span>
<span class="line"><span style="color: #66D9EF; font-style: italic">const</span><span style="color: #F8F8F2"> deep_o </span><span style="color: #F92672">=</span><span style="color: #F8F8F2"> </span><span style="color: #A6E22E">deep_clone</span><span style="color: #F8F8F2">(o)</span></span>
<span class="line"><span style="color: #F8F8F2">console.</span><span style="color: #A6E22E">log</span><span style="color: #F8F8F2">(deep_o) </span><span style="color: #88846F">// { a: {} }</span></span>
<span class="line"></span></code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></div></template>
